// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: artifact.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArtifactData chứa toàn bộ artifact set cho một contract
type ArtifactData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId      string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`                // keccak256(bytecode_hash + metadata)
	BytecodeHash    string                 `protobuf:"bytes,2,opt,name=bytecode_hash,json=bytecodeHash,proto3" json:"bytecode_hash,omitempty"`          // Hash của bytecode on-chain
	Metadata        string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                                      // Metadata/config.json (JSON string) - chứa compiler settings, sources, etc.
	Abi             string                 `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`                                                // ABI JSON string
	SourceCode      string                 `protobuf:"bytes,5,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`                // Full source code (all .sol files, JSON encoded)
	SourceMap       string                 `protobuf:"bytes,6,opt,name=source_map,json=sourceMap,proto3" json:"source_map,omitempty"`                   // Source map string
	StorageLayout   string                 `protobuf:"bytes,7,opt,name=storage_layout,json=storageLayout,proto3" json:"storage_layout,omitempty"`       // Storage layout JSON string
	ContractAddress string                 `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address (optional, for indexing)
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // Unix timestamp
	Verified        bool                   `protobuf:"varint,10,opt,name=verified,proto3" json:"verified,omitempty"`                                    // Whether artifact has been verified (bytecode match)
	VerifiedAt      int64                  `protobuf:"varint,11,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`              // Unix timestamp when verified
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArtifactData) Reset() {
	*x = ArtifactData{}
	mi := &file_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactData) ProtoMessage() {}

func (x *ArtifactData) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactData.ProtoReflect.Descriptor instead.
func (*ArtifactData) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactData) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactData) GetBytecodeHash() string {
	if x != nil {
		return x.BytecodeHash
	}
	return ""
}

func (x *ArtifactData) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *ArtifactData) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *ArtifactData) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ArtifactData) GetSourceMap() string {
	if x != nil {
		return x.SourceMap
	}
	return ""
}

func (x *ArtifactData) GetStorageLayout() string {
	if x != nil {
		return x.StorageLayout
	}
	return ""
}

func (x *ArtifactData) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ArtifactData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArtifactData) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ArtifactData) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

var File_artifact_proto protoreflect.FileDescriptor

const file_artifact_proto_rawDesc = "" +
	"\n" +
	"\x0eartifact.proto\x12\x05proto\"\xf0\x02\n" +
	"\fArtifactData\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rbytecode_hash\x18\x02 \x01(\tR\fbytecodeHash\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x10\n" +
	"\x03abi\x18\x04 \x01(\tR\x03abi\x12\x1f\n" +
	"\vsource_code\x18\x05 \x01(\tR\n" +
	"sourceCode\x12\x1d\n" +
	"\n" +
	"source_map\x18\x06 \x01(\tR\tsourceMap\x12%\n" +
	"\x0estorage_layout\x18\a \x01(\tR\rstorageLayout\x12)\n" +
	"\x10contract_address\x18\b \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bverified\x18\n" +
	" \x01(\bR\bverified\x12\x1f\n" +
	"\vverified_at\x18\v \x01(\x03R\n" +
	"verifiedAtB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_artifact_proto_rawDescOnce sync.Once
	file_artifact_proto_rawDescData []byte
)

func file_artifact_proto_rawDescGZIP() []byte {
	file_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)))
	})
	return file_artifact_proto_rawDescData
}

var file_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_artifact_proto_goTypes = []any{
	(*ArtifactData)(nil), // 0: proto.ArtifactData
}
var file_artifact_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_artifact_proto_init() }
func file_artifact_proto_init() {
	if File_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_proto_depIdxs,
		MessageInfos:      file_artifact_proto_msgTypes,
	}.Build()
	File_artifact_proto = out.File
	file_artifact_proto_goTypes = nil
	file_artifact_proto_depIdxs = nil
}
