// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block_vote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=Number,proto3" json:"Number,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Sign          []byte                 `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockVote) Reset() {
	*x = BlockVote{}
	mi := &file_block_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockVote) ProtoMessage() {}

func (x *BlockVote) ProtoReflect() protoreflect.Message {
	mi := &file_block_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockVote.ProtoReflect.Descriptor instead.
func (*BlockVote) Descriptor() ([]byte, []int) {
	return file_block_vote_proto_rawDescGZIP(), []int{0}
}

func (x *BlockVote) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockVote) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockVote) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *BlockVote) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

var File_block_vote_proto protoreflect.FileDescriptor

const file_block_vote_proto_rawDesc = "" +
	"\n" +
	"\x10block_vote.proto\x12\n" +
	"block_vote\"s\n" +
	"\tBlockVote\x12\x1c\n" +
	"\tBlockHash\x18\x01 \x01(\fR\tBlockHash\x12\x16\n" +
	"\x06Number\x18\x02 \x01(\x04R\x06Number\x12\x1c\n" +
	"\tPublicKey\x18\x03 \x01(\fR\tPublicKey\x12\x12\n" +
	"\x04Sign\x18\x04 \x01(\fR\x04SignB2\n" +
	"(com.meta_node.protos.compiled.block_voteZ\x06/protob\x06proto3"

var (
	file_block_vote_proto_rawDescOnce sync.Once
	file_block_vote_proto_rawDescData []byte
)

func file_block_vote_proto_rawDescGZIP() []byte {
	file_block_vote_proto_rawDescOnce.Do(func() {
		file_block_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_vote_proto_rawDesc), len(file_block_vote_proto_rawDesc)))
	})
	return file_block_vote_proto_rawDescData
}

var file_block_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_vote_proto_goTypes = []any{
	(*BlockVote)(nil), // 0: block_vote.BlockVote
}
var file_block_vote_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_vote_proto_init() }
func file_block_vote_proto_init() {
	if File_block_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_vote_proto_rawDesc), len(file_block_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_vote_proto_goTypes,
		DependencyIndexes: file_block_vote_proto_depIdxs,
		MessageInfos:      file_block_vote_proto_msgTypes,
	}.Build()
	File_block_vote_proto = out.File
	file_block_vote_proto_goTypes = nil
	file_block_vote_proto_depIdxs = nil
}
