// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LastBlockHash      []byte                 `protobuf:"bytes,1,opt,name=LastBlockHash,proto3" json:"LastBlockHash,omitempty"`
	BlockNumber        uint64                 `protobuf:"varint,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	AccountStatesRoot  []byte                 `protobuf:"bytes,3,opt,name=AccountStatesRoot,proto3" json:"AccountStatesRoot,omitempty"`
	ReceiptRoot        []byte                 `protobuf:"bytes,4,opt,name=ReceiptRoot,proto3" json:"ReceiptRoot,omitempty"`
	LeaderAddress      []byte                 `protobuf:"bytes,5,opt,name=LeaderAddress,proto3" json:"LeaderAddress,omitempty"`
	AggregateSignature []byte                 `protobuf:"bytes,6,opt,name=AggregateSignature,proto3" json:"AggregateSignature,omitempty"`
	TimeStamp          uint64                 `protobuf:"varint,7,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	TransactionsRoot   []byte                 `protobuf:"bytes,8,opt,name=TransactionsRoot,proto3" json:"TransactionsRoot,omitempty"`
	StakeStatesRoot    []byte                 `protobuf:"bytes,9,opt,name=StakeStatesRoot,proto3" json:"StakeStatesRoot,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetLastBlockHash() []byte {
	if x != nil {
		return x.LastBlockHash
	}
	return nil
}

func (x *BlockHeader) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockHeader) GetAccountStatesRoot() []byte {
	if x != nil {
		return x.AccountStatesRoot
	}
	return nil
}

func (x *BlockHeader) GetReceiptRoot() []byte {
	if x != nil {
		return x.ReceiptRoot
	}
	return nil
}

func (x *BlockHeader) GetLeaderAddress() []byte {
	if x != nil {
		return x.LeaderAddress
	}
	return nil
}

func (x *BlockHeader) GetAggregateSignature() []byte {
	if x != nil {
		return x.AggregateSignature
	}
	return nil
}

func (x *BlockHeader) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *BlockHeader) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

func (x *BlockHeader) GetStakeStatesRoot() []byte {
	if x != nil {
		return x.StakeStatesRoot
	}
	return nil
}

type Block struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Header           *BlockHeader           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Transactions     [][]byte               `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	ExecuteSCResults []*ExecuteSCResult     `protobuf:"bytes,3,rep,name=ExecuteSCResults,proto3" json:"ExecuteSCResults,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetExecuteSCResults() []*ExecuteSCResult {
	if x != nil {
		return x.ExecuteSCResults
	}
	return nil
}

type ConfirmedBlockData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *BlockHeader           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Receipts        []*Receipt             `protobuf:"bytes,2,rep,name=Receipts,proto3" json:"Receipts,omitempty"`
	BranchStateRoot []byte                 `protobuf:"bytes,3,opt,name=BranchStateRoot,proto3" json:"BranchStateRoot,omitempty"`
	ValidatorSigns  map[string][]byte      `protobuf:"bytes,4,rep,name=ValidatorSigns,proto3" json:"ValidatorSigns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmedBlockData) Reset() {
	*x = ConfirmedBlockData{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmedBlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedBlockData) ProtoMessage() {}

func (x *ConfirmedBlockData) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedBlockData.ProtoReflect.Descriptor instead.
func (*ConfirmedBlockData) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmedBlockData) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ConfirmedBlockData) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *ConfirmedBlockData) GetBranchStateRoot() []byte {
	if x != nil {
		return x.BranchStateRoot
	}
	return nil
}

func (x *ConfirmedBlockData) GetValidatorSigns() map[string][]byte {
	if x != nil {
		return x.ValidatorSigns
	}
	return nil
}

type BlockWithTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockWithTransactions) Reset() {
	*x = BlockWithTransactions{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockWithTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockWithTransactions) ProtoMessage() {}

func (x *BlockWithTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockWithTransactions.ProtoReflect.Descriptor instead.
func (*BlockWithTransactions) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *BlockWithTransactions) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockWithTransactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x05block\x1a\x11transaction.proto\x1a\rreceipt.proto\x1a\x14smart_contract.proto\"\xef\x02\n" +
	"\vBlockHeader\x12$\n" +
	"\rLastBlockHash\x18\x01 \x01(\fR\rLastBlockHash\x12 \n" +
	"\vBlockNumber\x18\x02 \x01(\x04R\vBlockNumber\x12,\n" +
	"\x11AccountStatesRoot\x18\x03 \x01(\fR\x11AccountStatesRoot\x12 \n" +
	"\vReceiptRoot\x18\x04 \x01(\fR\vReceiptRoot\x12$\n" +
	"\rLeaderAddress\x18\x05 \x01(\fR\rLeaderAddress\x12.\n" +
	"\x12AggregateSignature\x18\x06 \x01(\fR\x12AggregateSignature\x12\x1c\n" +
	"\tTimeStamp\x18\a \x01(\x04R\tTimeStamp\x12*\n" +
	"\x10TransactionsRoot\x18\b \x01(\fR\x10TransactionsRoot\x12(\n" +
	"\x0fStakeStatesRoot\x18\t \x01(\fR\x0fStakeStatesRoot\"\xa4\x01\n" +
	"\x05Block\x12*\n" +
	"\x06Header\x18\x01 \x01(\v2\x12.block.BlockHeaderR\x06Header\x12\"\n" +
	"\fTransactions\x18\x02 \x03(\fR\fTransactions\x12K\n" +
	"\x10ExecuteSCResults\x18\x03 \x03(\v2\x1f.smart_contract.ExecuteSCResultR\x10ExecuteSCResults\"\xb2\x02\n" +
	"\x12ConfirmedBlockData\x12*\n" +
	"\x06Header\x18\x01 \x01(\v2\x12.block.BlockHeaderR\x06Header\x12,\n" +
	"\bReceipts\x18\x02 \x03(\v2\x10.receipt.ReceiptR\bReceipts\x12(\n" +
	"\x0fBranchStateRoot\x18\x03 \x01(\fR\x0fBranchStateRoot\x12U\n" +
	"\x0eValidatorSigns\x18\x04 \x03(\v2-.block.ConfirmedBlockData.ValidatorSignsEntryR\x0eValidatorSigns\x1aA\n" +
	"\x13ValidatorSignsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"y\n" +
	"\x15BlockWithTransactions\x12\"\n" +
	"\x05block\x18\x01 \x01(\v2\f.block.BlockR\x05block\x12<\n" +
	"\ftransactions\x18\x02 \x03(\v2\x18.transaction.TransactionR\ftransactionsB-\n" +
	"#com.meta_node.protos.compiled.blockZ\x06/protob\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_block_proto_goTypes = []any{
	(*BlockHeader)(nil),           // 0: block.BlockHeader
	(*Block)(nil),                 // 1: block.Block
	(*ConfirmedBlockData)(nil),    // 2: block.ConfirmedBlockData
	(*BlockWithTransactions)(nil), // 3: block.BlockWithTransactions
	nil,                           // 4: block.ConfirmedBlockData.ValidatorSignsEntry
	(*ExecuteSCResult)(nil),       // 5: smart_contract.ExecuteSCResult
	(*Receipt)(nil),               // 6: receipt.Receipt
	(*Transaction)(nil),           // 7: transaction.Transaction
}
var file_block_proto_depIdxs = []int32{
	0, // 0: block.Block.Header:type_name -> block.BlockHeader
	5, // 1: block.Block.ExecuteSCResults:type_name -> smart_contract.ExecuteSCResult
	0, // 2: block.ConfirmedBlockData.Header:type_name -> block.BlockHeader
	6, // 3: block.ConfirmedBlockData.Receipts:type_name -> receipt.Receipt
	4, // 4: block.ConfirmedBlockData.ValidatorSigns:type_name -> block.ConfirmedBlockData.ValidatorSignsEntry
	1, // 5: block.BlockWithTransactions.block:type_name -> block.Block
	7, // 6: block.BlockWithTransactions.transactions:type_name -> transaction.Transaction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	file_transaction_proto_init()
	file_receipt_proto_init()
	file_smart_contract_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
