// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: checkpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatorWithStakeAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	StakeAmount   []byte                 `protobuf:"bytes,2,opt,name=StakeAmount,proto3" json:"StakeAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorWithStakeAmount) Reset() {
	*x = ValidatorWithStakeAmount{}
	mi := &file_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorWithStakeAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorWithStakeAmount) ProtoMessage() {}

func (x *ValidatorWithStakeAmount) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorWithStakeAmount.ProtoReflect.Descriptor instead.
func (*ValidatorWithStakeAmount) Descriptor() ([]byte, []int) {
	return file_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorWithStakeAmount) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ValidatorWithStakeAmount) GetStakeAmount() []byte {
	if x != nil {
		return x.StakeAmount
	}
	return nil
}

type ValidatorCheckPoint struct {
	state                       protoimpl.MessageState      `protogen:"open.v1"`
	BlockNumber                 uint64                      `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	PreValidatorWithStakeAmount []*ValidatorWithStakeAmount `protobuf:"bytes,2,rep,name=PreValidatorWithStakeAmount,proto3" json:"PreValidatorWithStakeAmount,omitempty"`
	ValidatorWithStakeAmount    []*ValidatorWithStakeAmount `protobuf:"bytes,3,rep,name=ValidatorWithStakeAmount,proto3" json:"ValidatorWithStakeAmount,omitempty"`
	ScheduleSeed                []byte                      `protobuf:"bytes,4,opt,name=ScheduleSeed,proto3" json:"ScheduleSeed,omitempty"`
	NextScheduleSeed            []byte                      `protobuf:"bytes,5,opt,name=NextScheduleSeed,proto3" json:"NextScheduleSeed,omitempty"`
	StakeStorageRoot            []byte                      `protobuf:"bytes,6,opt,name=StakeStorageRoot,proto3" json:"StakeStorageRoot,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ValidatorCheckPoint) Reset() {
	*x = ValidatorCheckPoint{}
	mi := &file_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorCheckPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorCheckPoint) ProtoMessage() {}

func (x *ValidatorCheckPoint) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorCheckPoint.ProtoReflect.Descriptor instead.
func (*ValidatorCheckPoint) Descriptor() ([]byte, []int) {
	return file_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorCheckPoint) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ValidatorCheckPoint) GetPreValidatorWithStakeAmount() []*ValidatorWithStakeAmount {
	if x != nil {
		return x.PreValidatorWithStakeAmount
	}
	return nil
}

func (x *ValidatorCheckPoint) GetValidatorWithStakeAmount() []*ValidatorWithStakeAmount {
	if x != nil {
		return x.ValidatorWithStakeAmount
	}
	return nil
}

func (x *ValidatorCheckPoint) GetScheduleSeed() []byte {
	if x != nil {
		return x.ScheduleSeed
	}
	return nil
}

func (x *ValidatorCheckPoint) GetNextScheduleSeed() []byte {
	if x != nil {
		return x.NextScheduleSeed
	}
	return nil
}

func (x *ValidatorCheckPoint) GetStakeStorageRoot() []byte {
	if x != nil {
		return x.StakeStorageRoot
	}
	return nil
}

var File_checkpoint_proto protoreflect.FileDescriptor

const file_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x10checkpoint.proto\x12\n" +
	"checkpoint\"V\n" +
	"\x18ValidatorWithStakeAmount\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12 \n" +
	"\vStakeAmount\x18\x02 \x01(\fR\vStakeAmount\"\xfd\x02\n" +
	"\x13ValidatorCheckPoint\x12 \n" +
	"\vBlockNumber\x18\x01 \x01(\x04R\vBlockNumber\x12f\n" +
	"\x1bPreValidatorWithStakeAmount\x18\x02 \x03(\v2$.checkpoint.ValidatorWithStakeAmountR\x1bPreValidatorWithStakeAmount\x12`\n" +
	"\x18ValidatorWithStakeAmount\x18\x03 \x03(\v2$.checkpoint.ValidatorWithStakeAmountR\x18ValidatorWithStakeAmount\x12\"\n" +
	"\fScheduleSeed\x18\x04 \x01(\fR\fScheduleSeed\x12*\n" +
	"\x10NextScheduleSeed\x18\x05 \x01(\fR\x10NextScheduleSeed\x12*\n" +
	"\x10StakeStorageRoot\x18\x06 \x01(\fR\x10StakeStorageRootB2\n" +
	"(com.meta_node.protos.compiled.checkpointZ\x06/protob\x06proto3"

var (
	file_checkpoint_proto_rawDescOnce sync.Once
	file_checkpoint_proto_rawDescData []byte
)

func file_checkpoint_proto_rawDescGZIP() []byte {
	file_checkpoint_proto_rawDescOnce.Do(func() {
		file_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkpoint_proto_rawDesc), len(file_checkpoint_proto_rawDesc)))
	})
	return file_checkpoint_proto_rawDescData
}

var file_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checkpoint_proto_goTypes = []any{
	(*ValidatorWithStakeAmount)(nil), // 0: checkpoint.ValidatorWithStakeAmount
	(*ValidatorCheckPoint)(nil),      // 1: checkpoint.ValidatorCheckPoint
}
var file_checkpoint_proto_depIdxs = []int32{
	0, // 0: checkpoint.ValidatorCheckPoint.PreValidatorWithStakeAmount:type_name -> checkpoint.ValidatorWithStakeAmount
	0, // 1: checkpoint.ValidatorCheckPoint.ValidatorWithStakeAmount:type_name -> checkpoint.ValidatorWithStakeAmount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_checkpoint_proto_init() }
func file_checkpoint_proto_init() {
	if File_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkpoint_proto_rawDesc), len(file_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checkpoint_proto_goTypes,
		DependencyIndexes: file_checkpoint_proto_depIdxs,
		MessageInfos:      file_checkpoint_proto_msgTypes,
	}.Build()
	File_checkpoint_proto = out.File
	file_checkpoint_proto_goTypes = nil
	file_checkpoint_proto_depIdxs = nil
}
