// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: contract_free_gas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractFreeGasData lưu thông tin contract được miễn phí gas
type ContractFreeGasData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress []byte                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // 20 bytes (Ethereum address)
	AddedAt         int64                  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`                        // Unix timestamp khi thêm vào
	AddedBy         []byte                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`                         // 20 bytes (địa chỉ Ethereum của người thêm)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractFreeGasData) Reset() {
	*x = ContractFreeGasData{}
	mi := &file_contract_free_gas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFreeGasData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFreeGasData) ProtoMessage() {}

func (x *ContractFreeGasData) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFreeGasData.ProtoReflect.Descriptor instead.
func (*ContractFreeGasData) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{0}
}

func (x *ContractFreeGasData) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *ContractFreeGasData) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *ContractFreeGasData) GetAddedBy() []byte {
	if x != nil {
		return x.AddedBy
	}
	return nil
}

// ContractFreeGasList dùng cho pagination response
type ContractFreeGasList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*ContractFreeGasData `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractFreeGasList) Reset() {
	*x = ContractFreeGasList{}
	mi := &file_contract_free_gas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFreeGasList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFreeGasList) ProtoMessage() {}

func (x *ContractFreeGasList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFreeGasList.ProtoReflect.Descriptor instead.
func (*ContractFreeGasList) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{1}
}

func (x *ContractFreeGasList) GetContracts() []*ContractFreeGasData {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ContractFreeGasList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ContractFreeGasList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContractFreeGasList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ContractFreeGasList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// AuthorizedWalletData lưu thông tin ví được cấp quyền
type AuthorizedWalletData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress []byte                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // 20 bytes (Ethereum address)
	AddedAt       int64                  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`                  // Unix timestamp khi được cấp quyền
	AddedBy       []byte                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`                   // 20 bytes (địa chỉ admin đã cấp quyền)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedWalletData) Reset() {
	*x = AuthorizedWalletData{}
	mi := &file_contract_free_gas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedWalletData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedWalletData) ProtoMessage() {}

func (x *AuthorizedWalletData) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedWalletData.ProtoReflect.Descriptor instead.
func (*AuthorizedWalletData) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizedWalletData) GetWalletAddress() []byte {
	if x != nil {
		return x.WalletAddress
	}
	return nil
}

func (x *AuthorizedWalletData) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *AuthorizedWalletData) GetAddedBy() []byte {
	if x != nil {
		return x.AddedBy
	}
	return nil
}

// AuthorizedWalletList dùng cho pagination response
type AuthorizedWalletList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Wallets       []*AuthorizedWalletData `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                   `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedWalletList) Reset() {
	*x = AuthorizedWalletList{}
	mi := &file_contract_free_gas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedWalletList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedWalletList) ProtoMessage() {}

func (x *AuthorizedWalletList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedWalletList.ProtoReflect.Descriptor instead.
func (*AuthorizedWalletList) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizedWalletList) GetWallets() []*AuthorizedWalletData {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *AuthorizedWalletList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AuthorizedWalletList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AuthorizedWalletList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AuthorizedWalletList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// AdminData lưu thông tin admin được cấp quyền
type AdminData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminAddress  []byte                 `protobuf:"bytes,1,opt,name=admin_address,json=adminAddress,proto3" json:"admin_address,omitempty"` // 20 bytes (Ethereum address)
	AddedAt       int64                  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`               // Unix timestamp khi được cấp quyền
	AddedBy       []byte                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`                // 20 bytes (root owner đã cấp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminData) Reset() {
	*x = AdminData{}
	mi := &file_contract_free_gas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminData) ProtoMessage() {}

func (x *AdminData) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminData.ProtoReflect.Descriptor instead.
func (*AdminData) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{4}
}

func (x *AdminData) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *AdminData) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *AdminData) GetAddedBy() []byte {
	if x != nil {
		return x.AddedBy
	}
	return nil
}

// AdminList dùng cho pagination response
type AdminList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminData           `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminList) Reset() {
	*x = AdminList{}
	mi := &file_contract_free_gas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminList) ProtoMessage() {}

func (x *AdminList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminList.ProtoReflect.Descriptor instead.
func (*AdminList) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{5}
}

func (x *AdminList) GetAdmins() []*AdminData {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *AdminList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_contract_free_gas_proto protoreflect.FileDescriptor

const file_contract_free_gas_proto_rawDesc = "" +
	"\n" +
	"\x17contract_free_gas.proto\x12\x05proto\"v\n" +
	"\x13ContractFreeGasData\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\fR\x0fcontractAddress\x12\x19\n" +
	"\badded_at\x18\x02 \x01(\x03R\aaddedAt\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\fR\aaddedBy\"\xb7\x01\n" +
	"\x13ContractFreeGasList\x128\n" +
	"\tcontracts\x18\x01 \x03(\v2\x1a.proto.ContractFreeGasDataR\tcontracts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"s\n" +
	"\x14AuthorizedWalletData\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\fR\rwalletAddress\x12\x19\n" +
	"\badded_at\x18\x02 \x01(\x03R\aaddedAt\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\fR\aaddedBy\"\xb5\x01\n" +
	"\x14AuthorizedWalletList\x125\n" +
	"\awallets\x18\x01 \x03(\v2\x1b.proto.AuthorizedWalletDataR\awallets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"f\n" +
	"\tAdminData\x12#\n" +
	"\radmin_address\x18\x01 \x01(\fR\fadminAddress\x12\x19\n" +
	"\badded_at\x18\x02 \x01(\x03R\aaddedAt\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\fR\aaddedBy\"\x9d\x01\n" +
	"\tAdminList\x12(\n" +
	"\x06admins\x18\x01 \x03(\v2\x10.proto.AdminDataR\x06admins\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPagesB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_contract_free_gas_proto_rawDescOnce sync.Once
	file_contract_free_gas_proto_rawDescData []byte
)

func file_contract_free_gas_proto_rawDescGZIP() []byte {
	file_contract_free_gas_proto_rawDescOnce.Do(func() {
		file_contract_free_gas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_free_gas_proto_rawDesc), len(file_contract_free_gas_proto_rawDesc)))
	})
	return file_contract_free_gas_proto_rawDescData
}

var file_contract_free_gas_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contract_free_gas_proto_goTypes = []any{
	(*ContractFreeGasData)(nil),  // 0: proto.ContractFreeGasData
	(*ContractFreeGasList)(nil),  // 1: proto.ContractFreeGasList
	(*AuthorizedWalletData)(nil), // 2: proto.AuthorizedWalletData
	(*AuthorizedWalletList)(nil), // 3: proto.AuthorizedWalletList
	(*AdminData)(nil),            // 4: proto.AdminData
	(*AdminList)(nil),            // 5: proto.AdminList
}
var file_contract_free_gas_proto_depIdxs = []int32{
	0, // 0: proto.ContractFreeGasList.contracts:type_name -> proto.ContractFreeGasData
	2, // 1: proto.AuthorizedWalletList.wallets:type_name -> proto.AuthorizedWalletData
	4, // 2: proto.AdminList.admins:type_name -> proto.AdminData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contract_free_gas_proto_init() }
func file_contract_free_gas_proto_init() {
	if File_contract_free_gas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_free_gas_proto_rawDesc), len(file_contract_free_gas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_free_gas_proto_goTypes,
		DependencyIndexes: file_contract_free_gas_proto_depIdxs,
		MessageInfos:      file_contract_free_gas_proto_msgTypes,
	}.Build()
	File_contract_free_gas_proto = out.File
	file_contract_free_gas_proto_goTypes = nil
	file_contract_free_gas_proto_depIdxs = nil
}
