// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: event_log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash []byte                 `protobuf:"bytes,2,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Address         []byte                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	Topics          [][]byte               `protobuf:"bytes,5,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_event_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{0}
}

func (x *EventLog) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *EventLog) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *EventLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventLog) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

type EventLogsHashData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLogsHashData) Reset() {
	*x = EventLogsHashData{}
	mi := &file_event_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLogsHashData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLogsHashData) ProtoMessage() {}

func (x *EventLogsHashData) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLogsHashData.ProtoReflect.Descriptor instead.
func (*EventLogsHashData) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{1}
}

func (x *EventLogsHashData) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type EventLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventLogs     []*EventLog            `protobuf:"bytes,1,rep,name=EventLogs,proto3" json:"EventLogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLogs) Reset() {
	*x = EventLogs{}
	mi := &file_event_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLogs) ProtoMessage() {}

func (x *EventLogs) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLogs.ProtoReflect.Descriptor instead.
func (*EventLogs) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{2}
}

func (x *EventLogs) GetEventLogs() []*EventLog {
	if x != nil {
		return x.EventLogs
	}
	return nil
}

// THÊM MESSAGE MỚI NÀY VÀO CUỐI FILE
type MapEventLogs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key là địa chỉ dạng hex string, value là danh sách các event log
	EventsByAddress map[string]*EventLogs `protobuf:"bytes,1,rep,name=events_by_address,json=eventsByAddress,proto3" json:"events_by_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapEventLogs) Reset() {
	*x = MapEventLogs{}
	mi := &file_event_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEventLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEventLogs) ProtoMessage() {}

func (x *MapEventLogs) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEventLogs.ProtoReflect.Descriptor instead.
func (*MapEventLogs) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{3}
}

func (x *MapEventLogs) GetEventsByAddress() map[string]*EventLogs {
	if x != nil {
		return x.EventsByAddress
	}
	return nil
}

// GetLogsRequest - Request để lấy logs theo filter criteria
type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"` // Optional: Hash của block cụ thể
	FromBlock     []byte                 `protobuf:"bytes,2,opt,name=FromBlock,proto3" json:"FromBlock,omitempty"` // Optional: Block bắt đầu (big.Int encoded)
	ToBlock       []byte                 `protobuf:"bytes,3,opt,name=ToBlock,proto3" json:"ToBlock,omitempty"`     // Optional: Block kết thúc (big.Int encoded)
	Addresses     [][]byte               `protobuf:"bytes,4,rep,name=Addresses,proto3" json:"Addresses,omitempty"` // Optional: Danh sách địa chỉ contract cần filter
	Topics        []*TopicFilter         `protobuf:"bytes,5,rep,name=Topics,proto3" json:"Topics,omitempty"`       // Optional: Danh sách topics để filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_event_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogsRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *GetLogsRequest) GetFromBlock() []byte {
	if x != nil {
		return x.FromBlock
	}
	return nil
}

func (x *GetLogsRequest) GetToBlock() []byte {
	if x != nil {
		return x.ToBlock
	}
	return nil
}

func (x *GetLogsRequest) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetLogsRequest) GetTopics() []*TopicFilter {
	if x != nil {
		return x.Topics
	}
	return nil
}

// TopicFilter - Filter cho một topic position
type TopicFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=Hashes,proto3" json:"Hashes,omitempty"` // Danh sách các hash có thể cho topic này
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicFilter) Reset() {
	*x = TopicFilter{}
	mi := &file_event_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicFilter) ProtoMessage() {}

func (x *TopicFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicFilter.ProtoReflect.Descriptor instead.
func (*TopicFilter) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{5}
}

func (x *TopicFilter) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// GetLogsResponse - Response chứa danh sách logs
type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=Logs,proto3" json:"Logs,omitempty"`   // Danh sách các log entries
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"` // Error message nếu có lỗi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_event_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{6}
}

func (x *GetLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LogEntry - Một entry log từ smart contract
type LogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          []byte                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`                    // Địa chỉ contract phát sinh log
	Topics           [][]byte               `protobuf:"bytes,2,rep,name=Topics,proto3" json:"Topics,omitempty"`                      // Danh sách topics
	Data             []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`                          // Dữ liệu log
	BlockNumber      uint64                 `protobuf:"varint,4,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`           // Block number chứa log
	TransactionHash  []byte                 `protobuf:"bytes,5,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`    // Hash của transaction
	BlockHash        []byte                 `protobuf:"bytes,6,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`                // Hash của block
	TransactionIndex uint64                 `protobuf:"varint,7,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"` // Index của transaction trong block
	LogIndex         uint64                 `protobuf:"varint,8,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`                 // Index của log trong transaction
	Removed          bool                   `protobuf:"varint,9,opt,name=Removed,proto3" json:"Removed,omitempty"`                   // Có bị removed không (reorg)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_event_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_event_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_event_log_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *LogEntry) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEntry) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *LogEntry) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *LogEntry) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *LogEntry) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *LogEntry) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *LogEntry) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_event_log_proto protoreflect.FileDescriptor

const file_event_log_proto_rawDesc = "" +
	"\n" +
	"\x0fevent_log.proto\x12\tevent_log\"z\n" +
	"\bEventLog\x12(\n" +
	"\x0fTransactionHash\x18\x02 \x01(\fR\x0fTransactionHash\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\fR\aAddress\x12\x12\n" +
	"\x04Data\x18\x04 \x01(\fR\x04Data\x12\x16\n" +
	"\x06Topics\x18\x05 \x03(\fR\x06Topics\"+\n" +
	"\x11EventLogsHashData\x12\x16\n" +
	"\x06Hashes\x18\x01 \x03(\fR\x06Hashes\">\n" +
	"\tEventLogs\x121\n" +
	"\tEventLogs\x18\x01 \x03(\v2\x13.event_log.EventLogR\tEventLogs\"\xc2\x01\n" +
	"\fMapEventLogs\x12X\n" +
	"\x11events_by_address\x18\x01 \x03(\v2,.event_log.MapEventLogs.EventsByAddressEntryR\x0feventsByAddress\x1aX\n" +
	"\x14EventsByAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.event_log.EventLogsR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x0eGetLogsRequest\x12\x1c\n" +
	"\tBlockHash\x18\x01 \x01(\fR\tBlockHash\x12\x1c\n" +
	"\tFromBlock\x18\x02 \x01(\fR\tFromBlock\x12\x18\n" +
	"\aToBlock\x18\x03 \x01(\fR\aToBlock\x12\x1c\n" +
	"\tAddresses\x18\x04 \x03(\fR\tAddresses\x12.\n" +
	"\x06Topics\x18\x05 \x03(\v2\x16.event_log.TopicFilterR\x06Topics\"%\n" +
	"\vTopicFilter\x12\x16\n" +
	"\x06Hashes\x18\x01 \x03(\fR\x06Hashes\"P\n" +
	"\x0fGetLogsResponse\x12'\n" +
	"\x04Logs\x18\x01 \x03(\v2\x13.event_log.LogEntryR\x04Logs\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"\x9c\x02\n" +
	"\bLogEntry\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12\x16\n" +
	"\x06Topics\x18\x02 \x03(\fR\x06Topics\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12 \n" +
	"\vBlockNumber\x18\x04 \x01(\x04R\vBlockNumber\x12(\n" +
	"\x0fTransactionHash\x18\x05 \x01(\fR\x0fTransactionHash\x12\x1c\n" +
	"\tBlockHash\x18\x06 \x01(\fR\tBlockHash\x12*\n" +
	"\x10TransactionIndex\x18\a \x01(\x04R\x10TransactionIndex\x12\x1a\n" +
	"\bLogIndex\x18\b \x01(\x04R\bLogIndex\x12\x18\n" +
	"\aRemoved\x18\t \x01(\bR\aRemovedB1\n" +
	"'com.meta_node.protos.compiled.event_logZ\x06/protob\x06proto3"

var (
	file_event_log_proto_rawDescOnce sync.Once
	file_event_log_proto_rawDescData []byte
)

func file_event_log_proto_rawDescGZIP() []byte {
	file_event_log_proto_rawDescOnce.Do(func() {
		file_event_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_log_proto_rawDesc), len(file_event_log_proto_rawDesc)))
	})
	return file_event_log_proto_rawDescData
}

var file_event_log_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_event_log_proto_goTypes = []any{
	(*EventLog)(nil),          // 0: event_log.EventLog
	(*EventLogsHashData)(nil), // 1: event_log.EventLogsHashData
	(*EventLogs)(nil),         // 2: event_log.EventLogs
	(*MapEventLogs)(nil),      // 3: event_log.MapEventLogs
	(*GetLogsRequest)(nil),    // 4: event_log.GetLogsRequest
	(*TopicFilter)(nil),       // 5: event_log.TopicFilter
	(*GetLogsResponse)(nil),   // 6: event_log.GetLogsResponse
	(*LogEntry)(nil),          // 7: event_log.LogEntry
	nil,                       // 8: event_log.MapEventLogs.EventsByAddressEntry
}
var file_event_log_proto_depIdxs = []int32{
	0, // 0: event_log.EventLogs.EventLogs:type_name -> event_log.EventLog
	8, // 1: event_log.MapEventLogs.events_by_address:type_name -> event_log.MapEventLogs.EventsByAddressEntry
	5, // 2: event_log.GetLogsRequest.Topics:type_name -> event_log.TopicFilter
	7, // 3: event_log.GetLogsResponse.Logs:type_name -> event_log.LogEntry
	2, // 4: event_log.MapEventLogs.EventsByAddressEntry.value:type_name -> event_log.EventLogs
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_event_log_proto_init() }
func file_event_log_proto_init() {
	if File_event_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_log_proto_rawDesc), len(file_event_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_log_proto_goTypes,
		DependencyIndexes: file_event_log_proto_depIdxs,
		MessageInfos:      file_event_log_proto_msgTypes,
	}.Build()
	File_event_log_proto = out.File
	file_event_log_proto_goTypes = nil
	file_event_log_proto_depIdxs = nil
}
