// grouptxns.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: grouptxns.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Định nghĩa cho message RelativeGroup
type RelativeGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   int32    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Items     []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Relatives [][]byte `protobuf:"bytes,3,rep,name=relatives,proto3" json:"relatives,omitempty"`
}

func (x *RelativeGroup) Reset() {
	*x = RelativeGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grouptxns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelativeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeGroup) ProtoMessage() {}

func (x *RelativeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_grouptxns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeGroup.ProtoReflect.Descriptor instead.
func (*RelativeGroup) Descriptor() ([]byte, []int) {
	return file_grouptxns_proto_rawDescGZIP(), []int{0}
}

func (x *RelativeGroup) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RelativeGroup) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RelativeGroup) GetRelatives() [][]byte {
	if x != nil {
		return x.Relatives
	}
	return nil
}

// Định nghĩa cho message Item
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Array   [][]byte `protobuf:"bytes,2,rep,name=array,proto3" json:"array,omitempty"`
	GroupId int32    `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Sử dụng message Transaction đã được import
	Tx *Transaction `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	// Sử dụng int64 để lưu Unix timestamp (số giây)
	TimeStart int64 `protobuf:"varint,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grouptxns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_grouptxns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_grouptxns_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetArray() [][]byte {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Item) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *Item) GetTimeStart() int64 {
	if x != nil {
		return x.TimeStart
	}
	return 0
}

var File_grouptxns_proto protoreflect.FileDescriptor

var file_grouptxns_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x74, 0x78, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x74, 0x78, 0x6e, 0x73, 0x1a, 0x11, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6f, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x74, 0x78, 0x6e, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x22, 0x90, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x72,
	0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x02, 0x74, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x02, 0x74, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grouptxns_proto_rawDescOnce sync.Once
	file_grouptxns_proto_rawDescData = file_grouptxns_proto_rawDesc
)

func file_grouptxns_proto_rawDescGZIP() []byte {
	file_grouptxns_proto_rawDescOnce.Do(func() {
		file_grouptxns_proto_rawDescData = protoimpl.X.CompressGZIP(file_grouptxns_proto_rawDescData)
	})
	return file_grouptxns_proto_rawDescData
}

var file_grouptxns_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grouptxns_proto_goTypes = []interface{}{
	(*RelativeGroup)(nil), // 0: grouptxns.RelativeGroup
	(*Item)(nil),          // 1: grouptxns.Item
	(*Transaction)(nil),   // 2: transaction.Transaction
}
var file_grouptxns_proto_depIdxs = []int32{
	1, // 0: grouptxns.RelativeGroup.items:type_name -> grouptxns.Item
	2, // 1: grouptxns.Item.tx:type_name -> transaction.Transaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grouptxns_proto_init() }
func file_grouptxns_proto_init() {
	if File_grouptxns_proto != nil {
		return
	}
	file_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grouptxns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelativeGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grouptxns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grouptxns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grouptxns_proto_goTypes,
		DependencyIndexes: file_grouptxns_proto_depIdxs,
		MessageInfos:      file_grouptxns_proto_msgTypes,
	}.Build()
	File_grouptxns_proto = out.File
	file_grouptxns_proto_rawDesc = nil
	file_grouptxns_proto_goTypes = nil
	file_grouptxns_proto_depIdxs = nil
}
