// proto/rpc_commands.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: mining.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common types
type Hash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hash) Reset() {
	*x = Hash{}
	mi := &file_mining_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{0}
}

func (x *Hash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 20 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_mining_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Request/Response for GetExecuteSCResultsHash
type GetExecuteSCResultsHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecuteSCResultsHashRequest) Reset() {
	*x = GetExecuteSCResultsHashRequest{}
	mi := &file_mining_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecuteSCResultsHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecuteSCResultsHashRequest) ProtoMessage() {}

func (x *GetExecuteSCResultsHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecuteSCResultsHashRequest.ProtoReflect.Descriptor instead.
func (*GetExecuteSCResultsHashRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecuteSCResultsHashRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type GetExecuteSCResultsHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *Hash                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecuteSCResultsHashResponse) Reset() {
	*x = GetExecuteSCResultsHashResponse{}
	mi := &file_mining_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecuteSCResultsHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecuteSCResultsHashResponse) ProtoMessage() {}

func (x *GetExecuteSCResultsHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecuteSCResultsHashResponse.ProtoReflect.Descriptor instead.
func (*GetExecuteSCResultsHashResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{3}
}

func (x *GetExecuteSCResultsHashResponse) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Request/Response for SendRawTransactionWithDeviceKey
type SendRawTransactionWithDeviceKeyRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	RawTransactionWithDeviceKey []byte                 `protobuf:"bytes,1,opt,name=raw_transaction_with_device_key,json=rawTransactionWithDeviceKey,proto3" json:"raw_transaction_with_device_key,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SendRawTransactionWithDeviceKeyRequest) Reset() {
	*x = SendRawTransactionWithDeviceKeyRequest{}
	mi := &file_mining_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRawTransactionWithDeviceKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRawTransactionWithDeviceKeyRequest) ProtoMessage() {}

func (x *SendRawTransactionWithDeviceKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRawTransactionWithDeviceKeyRequest.ProtoReflect.Descriptor instead.
func (*SendRawTransactionWithDeviceKeyRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{4}
}

func (x *SendRawTransactionWithDeviceKeyRequest) GetRawTransactionWithDeviceKey() []byte {
	if x != nil {
		return x.RawTransactionWithDeviceKey
	}
	return nil
}

type SendRawTransactionWithDeviceKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        *Hash                  `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRawTransactionWithDeviceKeyResponse) Reset() {
	*x = SendRawTransactionWithDeviceKeyResponse{}
	mi := &file_mining_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRawTransactionWithDeviceKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRawTransactionWithDeviceKeyResponse) ProtoMessage() {}

func (x *SendRawTransactionWithDeviceKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRawTransactionWithDeviceKeyResponse.ProtoReflect.Descriptor instead.
func (*SendRawTransactionWithDeviceKeyResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{5}
}

func (x *SendRawTransactionWithDeviceKeyResponse) GetTxHash() *Hash {
	if x != nil {
		return x.TxHash
	}
	return nil
}

// Request/Response for GetDeviceKey
type GetDeviceKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *Hash                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceKeyRequest) Reset() {
	*x = GetDeviceKeyRequest{}
	mi := &file_mining_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceKeyRequest) ProtoMessage() {}

func (x *GetDeviceKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceKeyRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceKeyRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeviceKeyRequest) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetDeviceKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey     *Hash                  `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceKeyResponse) Reset() {
	*x = GetDeviceKeyResponse{}
	mi := &file_mining_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceKeyResponse) ProtoMessage() {}

func (x *GetDeviceKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceKeyResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceKeyResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceKeyResponse) GetDeviceKey() *Hash {
	if x != nil {
		return x.DeviceKey
	}
	return nil
}

// Request/Response for GetAccountState
type GetAccountStateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Types that are valid to be assigned to BlockIdentifier:
	//
	//	*GetAccountStateRequest_BlockNumber
	//	*GetAccountStateRequest_BlockHash
	BlockIdentifier isGetAccountStateRequest_BlockIdentifier `protobuf_oneof:"block_identifier"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAccountStateRequest) Reset() {
	*x = GetAccountStateRequest{}
	mi := &file_mining_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStateRequest) ProtoMessage() {}

func (x *GetAccountStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStateRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountStateRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetAccountStateRequest) GetBlockIdentifier() isGetAccountStateRequest_BlockIdentifier {
	if x != nil {
		return x.BlockIdentifier
	}
	return nil
}

func (x *GetAccountStateRequest) GetBlockNumber() uint64 {
	if x != nil {
		if x, ok := x.BlockIdentifier.(*GetAccountStateRequest_BlockNumber); ok {
			return x.BlockNumber
		}
	}
	return 0
}

func (x *GetAccountStateRequest) GetBlockHash() *Hash {
	if x != nil {
		if x, ok := x.BlockIdentifier.(*GetAccountStateRequest_BlockHash); ok {
			return x.BlockHash
		}
	}
	return nil
}

type isGetAccountStateRequest_BlockIdentifier interface {
	isGetAccountStateRequest_BlockIdentifier()
}

type GetAccountStateRequest_BlockNumber struct {
	BlockNumber uint64 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3,oneof"`
}

type GetAccountStateRequest_BlockHash struct {
	BlockHash *Hash `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3,oneof"`
}

func (*GetAccountStateRequest_BlockNumber) isGetAccountStateRequest_BlockIdentifier() {}

func (*GetAccountStateRequest_BlockHash) isGetAccountStateRequest_BlockIdentifier() {}

type GetAccountStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance        string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	PendingBalance string                 `protobuf:"bytes,3,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	DeviceKey      *Hash                  `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	LastHash       *Hash                  `protobuf:"bytes,5,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	PublicKeyBls   string                 `protobuf:"bytes,6,opt,name=public_key_bls,json=publicKeyBls,proto3" json:"public_key_bls,omitempty"`
	Nonce          uint64                 `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountType    uint32                 `protobuf:"varint,8,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccountStateResponse) Reset() {
	*x = GetAccountStateResponse{}
	mi := &file_mining_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStateResponse) ProtoMessage() {}

func (x *GetAccountStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStateResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountStateResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAccountStateResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetAccountStateResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *GetAccountStateResponse) GetDeviceKey() *Hash {
	if x != nil {
		return x.DeviceKey
	}
	return nil
}

func (x *GetAccountStateResponse) GetLastHash() *Hash {
	if x != nil {
		return x.LastHash
	}
	return nil
}

func (x *GetAccountStateResponse) GetPublicKeyBls() string {
	if x != nil {
		return x.PublicKeyBls
	}
	return ""
}

func (x *GetAccountStateResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetAccountStateResponse) GetAccountType() uint32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

// Request/Response for SearchTransactions
type SearchTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTransactionsRequest) Reset() {
	*x = SearchTransactionsRequest{}
	mi := &file_mining_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransactionsRequest) ProtoMessage() {}

func (x *SearchTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransactionsRequest.ProtoReflect.Descriptor instead.
func (*SearchTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{10}
}

func (x *SearchTransactionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchTransactionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Total            uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	TransactionsJson []string               `protobuf:"bytes,2,rep,name=transactions_json,json=transactionsJson,proto3" json:"transactions_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchTransactionsResponse) Reset() {
	*x = SearchTransactionsResponse{}
	mi := &file_mining_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransactionsResponse) ProtoMessage() {}

func (x *SearchTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransactionsResponse.ProtoReflect.Descriptor instead.
func (*SearchTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{11}
}

func (x *SearchTransactionsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchTransactionsResponse) GetTransactionsJson() []string {
	if x != nil {
		return x.TransactionsJson
	}
	return nil
}

// Request/Response for GetJob
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_mining_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Creator       string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Assignee      string                 `protobuf:"bytes,3,opt,name=assignee,proto3" json:"assignee,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Data          string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Reward        float64                `protobuf:"fixed64,7,opt,name=reward,proto3" json:"reward,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	TxHash        string                 `protobuf:"bytes,10,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_mining_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{13}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Job) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Job) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *Job) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Job) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Job) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_mining_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// Request/Response for CompleteJob
type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	HashExecute   *Hash                  `protobuf:"bytes,3,opt,name=hash_execute,json=hashExecute,proto3" json:"hash_execute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_mining_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteJobRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobRequest) GetHashExecute() *Hash {
	if x != nil {
		return x.HashExecute
	}
	return nil
}

type CompleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobResponse) Reset() {
	*x = CompleteJobResponse{}
	mi := &file_mining_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobResponse) ProtoMessage() {}

func (x *CompleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request/Response for GetTransactionHistoryByAddress
type GetTransactionHistoryByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryByAddressRequest) Reset() {
	*x = GetTransactionHistoryByAddressRequest{}
	mi := &file_mining_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryByAddressRequest) ProtoMessage() {}

func (x *GetTransactionHistoryByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryByAddressRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{17}
}

func (x *GetTransactionHistoryByAddressRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetTransactionHistoryByAddressRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTransactionHistoryByAddressRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TransactionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRecord) Reset() {
	*x = TransactionRecord{}
	mi := &file_mining_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRecord) ProtoMessage() {}

func (x *TransactionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRecord.ProtoReflect.Descriptor instead.
func (*TransactionRecord) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{18}
}

func (x *TransactionRecord) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionRecord) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TransactionRecord) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionRecord) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TransactionRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ĐÃ SỬA: Thêm trường `error`
type GetTransactionHistoryByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*TransactionRecord   `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // Bổ sung trường này
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryByAddressResponse) Reset() {
	*x = GetTransactionHistoryByAddressResponse{}
	mi := &file_mining_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryByAddressResponse) ProtoMessage() {}

func (x *GetTransactionHistoryByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryByAddressResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionHistoryByAddressResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionHistoryByAddressResponse) GetRecords() []*TransactionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetTransactionHistoryByAddressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request/Response for GetTransactionHistoryByJobID
type GetTransactionHistoryByJobIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryByJobIDRequest) Reset() {
	*x = GetTransactionHistoryByJobIDRequest{}
	mi := &file_mining_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryByJobIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryByJobIDRequest) ProtoMessage() {}

func (x *GetTransactionHistoryByJobIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryByJobIDRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryByJobIDRequest) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{20}
}

func (x *GetTransactionHistoryByJobIDRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// ĐÃ SỬA: Thêm trường `error`
type GetTransactionHistoryByJobIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *TransactionRecord     `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Bổ sung trường này
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryByJobIDResponse) Reset() {
	*x = GetTransactionHistoryByJobIDResponse{}
	mi := &file_mining_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryByJobIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryByJobIDResponse) ProtoMessage() {}

func (x *GetTransactionHistoryByJobIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mining_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryByJobIDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryByJobIDResponse) Descriptor() ([]byte, []int) {
	return file_mining_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransactionHistoryByJobIDResponse) GetRecord() *TransactionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetTransactionHistoryByJobIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mining_proto protoreflect.FileDescriptor

const file_mining_proto_rawDesc = "" +
	"\n" +
	"\fmining.proto\x12\x06mining\"\x1c\n" +
	"\x04Hash\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x1f\n" +
	"\aAddress\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"C\n" +
	"\x1eGetExecuteSCResultsHashRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"C\n" +
	"\x1fGetExecuteSCResultsHashResponse\x12 \n" +
	"\x04hash\x18\x01 \x01(\v2\f.mining.HashR\x04hash\"n\n" +
	"&SendRawTransactionWithDeviceKeyRequest\x12D\n" +
	"\x1fraw_transaction_with_device_key\x18\x01 \x01(\fR\x1brawTransactionWithDeviceKey\"P\n" +
	"'SendRawTransactionWithDeviceKeyResponse\x12%\n" +
	"\atx_hash\x18\x01 \x01(\v2\f.mining.HashR\x06txHash\"7\n" +
	"\x13GetDeviceKeyRequest\x12 \n" +
	"\x04hash\x18\x01 \x01(\v2\f.mining.HashR\x04hash\"C\n" +
	"\x14GetDeviceKeyResponse\x12+\n" +
	"\n" +
	"device_key\x18\x01 \x01(\v2\f.mining.HashR\tdeviceKey\"\xab\x01\n" +
	"\x16GetAccountStateRequest\x12)\n" +
	"\aaddress\x18\x01 \x01(\v2\x0f.mining.AddressR\aaddress\x12#\n" +
	"\fblock_number\x18\x02 \x01(\x04H\x00R\vblockNumber\x12-\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\v2\f.mining.HashH\x00R\tblockHashB\x12\n" +
	"\x10block_identifier\"\xad\x02\n" +
	"\x17GetAccountStateResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12'\n" +
	"\x0fpending_balance\x18\x03 \x01(\tR\x0ependingBalance\x12+\n" +
	"\n" +
	"device_key\x18\x04 \x01(\v2\f.mining.HashR\tdeviceKey\x12)\n" +
	"\tlast_hash\x18\x05 \x01(\v2\f.mining.HashR\blastHash\x12$\n" +
	"\x0epublic_key_bls\x18\x06 \x01(\tR\fpublicKeyBls\x12\x14\n" +
	"\x05nonce\x18\a \x01(\x04R\x05nonce\x12!\n" +
	"\faccount_type\x18\b \x01(\rR\vaccountType\"_\n" +
	"\x19SearchTransactionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"_\n" +
	"\x1aSearchTransactionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12+\n" +
	"\x11transactions_json\x18\x02 \x03(\tR\x10transactionsJson\":\n" +
	"\rGetJobRequest\x12)\n" +
	"\aaddress\x18\x01 \x01(\v2\x0f.mining.AddressR\aaddress\"\x8c\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12\x1a\n" +
	"\bassignee\x18\x03 \x01(\tR\bassignee\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x16\n" +
	"\x06reward\x18\a \x01(\x01R\x06reward\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\x03R\vcompletedAt\x12\x17\n" +
	"\atx_hash\x18\n" +
	" \x01(\tR\x06txHash\"/\n" +
	"\x0eGetJobResponse\x12\x1d\n" +
	"\x03job\x18\x01 \x01(\v2\v.mining.JobR\x03job\"\x87\x01\n" +
	"\x12CompleteJobRequest\x12)\n" +
	"\aaddress\x18\x01 \x01(\v2\x0f.mining.AddressR\aaddress\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12/\n" +
	"\fhash_execute\x18\x03 \x01(\v2\f.mining.HashR\vhashExecute\"/\n" +
	"\x13CompleteJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x80\x01\n" +
	"%GetTransactionHistoryByAddressRequest\x12)\n" +
	"\aaddress\x18\x01 \x01(\v2\x0f.mining.AddressR\aaddress\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc3\x01\n" +
	"\x11TransactionRecord\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x89\x01\n" +
	"&GetTransactionHistoryByAddressResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x123\n" +
	"\arecords\x18\x02 \x03(\v2\x19.mining.TransactionRecordR\arecords\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"#GetTransactionHistoryByJobIDRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"o\n" +
	"$GetTransactionHistoryByJobIDResponse\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.mining.TransactionRecordR\x06record\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\bZ\x06/protob\x06proto3"

var (
	file_mining_proto_rawDescOnce sync.Once
	file_mining_proto_rawDescData []byte
)

func file_mining_proto_rawDescGZIP() []byte {
	file_mining_proto_rawDescOnce.Do(func() {
		file_mining_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mining_proto_rawDesc), len(file_mining_proto_rawDesc)))
	})
	return file_mining_proto_rawDescData
}

var file_mining_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_mining_proto_goTypes = []any{
	(*Hash)(nil),                                    // 0: mining.Hash
	(*Address)(nil),                                 // 1: mining.Address
	(*GetExecuteSCResultsHashRequest)(nil),          // 2: mining.GetExecuteSCResultsHashRequest
	(*GetExecuteSCResultsHashResponse)(nil),         // 3: mining.GetExecuteSCResultsHashResponse
	(*SendRawTransactionWithDeviceKeyRequest)(nil),  // 4: mining.SendRawTransactionWithDeviceKeyRequest
	(*SendRawTransactionWithDeviceKeyResponse)(nil), // 5: mining.SendRawTransactionWithDeviceKeyResponse
	(*GetDeviceKeyRequest)(nil),                     // 6: mining.GetDeviceKeyRequest
	(*GetDeviceKeyResponse)(nil),                    // 7: mining.GetDeviceKeyResponse
	(*GetAccountStateRequest)(nil),                  // 8: mining.GetAccountStateRequest
	(*GetAccountStateResponse)(nil),                 // 9: mining.GetAccountStateResponse
	(*SearchTransactionsRequest)(nil),               // 10: mining.SearchTransactionsRequest
	(*SearchTransactionsResponse)(nil),              // 11: mining.SearchTransactionsResponse
	(*GetJobRequest)(nil),                           // 12: mining.GetJobRequest
	(*Job)(nil),                                     // 13: mining.Job
	(*GetJobResponse)(nil),                          // 14: mining.GetJobResponse
	(*CompleteJobRequest)(nil),                      // 15: mining.CompleteJobRequest
	(*CompleteJobResponse)(nil),                     // 16: mining.CompleteJobResponse
	(*GetTransactionHistoryByAddressRequest)(nil),   // 17: mining.GetTransactionHistoryByAddressRequest
	(*TransactionRecord)(nil),                       // 18: mining.TransactionRecord
	(*GetTransactionHistoryByAddressResponse)(nil),  // 19: mining.GetTransactionHistoryByAddressResponse
	(*GetTransactionHistoryByJobIDRequest)(nil),     // 20: mining.GetTransactionHistoryByJobIDRequest
	(*GetTransactionHistoryByJobIDResponse)(nil),    // 21: mining.GetTransactionHistoryByJobIDResponse
}
var file_mining_proto_depIdxs = []int32{
	0,  // 0: mining.GetExecuteSCResultsHashResponse.hash:type_name -> mining.Hash
	0,  // 1: mining.SendRawTransactionWithDeviceKeyResponse.tx_hash:type_name -> mining.Hash
	0,  // 2: mining.GetDeviceKeyRequest.hash:type_name -> mining.Hash
	0,  // 3: mining.GetDeviceKeyResponse.device_key:type_name -> mining.Hash
	1,  // 4: mining.GetAccountStateRequest.address:type_name -> mining.Address
	0,  // 5: mining.GetAccountStateRequest.block_hash:type_name -> mining.Hash
	0,  // 6: mining.GetAccountStateResponse.device_key:type_name -> mining.Hash
	0,  // 7: mining.GetAccountStateResponse.last_hash:type_name -> mining.Hash
	1,  // 8: mining.GetJobRequest.address:type_name -> mining.Address
	13, // 9: mining.GetJobResponse.job:type_name -> mining.Job
	1,  // 10: mining.CompleteJobRequest.address:type_name -> mining.Address
	0,  // 11: mining.CompleteJobRequest.hash_execute:type_name -> mining.Hash
	1,  // 12: mining.GetTransactionHistoryByAddressRequest.address:type_name -> mining.Address
	18, // 13: mining.GetTransactionHistoryByAddressResponse.records:type_name -> mining.TransactionRecord
	18, // 14: mining.GetTransactionHistoryByJobIDResponse.record:type_name -> mining.TransactionRecord
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mining_proto_init() }
func file_mining_proto_init() {
	if File_mining_proto != nil {
		return
	}
	file_mining_proto_msgTypes[8].OneofWrappers = []any{
		(*GetAccountStateRequest_BlockNumber)(nil),
		(*GetAccountStateRequest_BlockHash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mining_proto_rawDesc), len(file_mining_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mining_proto_goTypes,
		DependencyIndexes: file_mining_proto_depIdxs,
		MessageInfos:      file_mining_proto_msgTypes,
	}.Build()
	File_mining_proto = out.File
	file_mining_proto_goTypes = nil
	file_mining_proto_depIdxs = nil
}
