// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: receipt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RECEIPT_PROCESSING_TYPE int32

const (
	RECEIPT_PROCESSING_TYPE_POST_COMMIT_NOTIFICATION RECEIPT_PROCESSING_TYPE = 0 // Thông báo sau commit (mặc định)
	RECEIPT_PROCESSING_TYPE_PRE_COMMIT_NOTIFICATION  RECEIPT_PROCESSING_TYPE = 1 // Thông báo trước commit
)

// Enum value maps for RECEIPT_PROCESSING_TYPE.
var (
	RECEIPT_PROCESSING_TYPE_name = map[int32]string{
		0: "POST_COMMIT_NOTIFICATION",
		1: "PRE_COMMIT_NOTIFICATION",
	}
	RECEIPT_PROCESSING_TYPE_value = map[string]int32{
		"POST_COMMIT_NOTIFICATION": 0,
		"PRE_COMMIT_NOTIFICATION":  1,
	}
)

func (x RECEIPT_PROCESSING_TYPE) Enum() *RECEIPT_PROCESSING_TYPE {
	p := new(RECEIPT_PROCESSING_TYPE)
	*p = x
	return p
}

func (x RECEIPT_PROCESSING_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RECEIPT_PROCESSING_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_receipt_proto_enumTypes[0].Descriptor()
}

func (RECEIPT_PROCESSING_TYPE) Type() protoreflect.EnumType {
	return &file_receipt_proto_enumTypes[0]
}

func (x RECEIPT_PROCESSING_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RECEIPT_PROCESSING_TYPE.Descriptor instead.
func (RECEIPT_PROCESSING_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{0}
}

type RECEIPT_STATUS int32

const (
	RECEIPT_STATUS_RETURNED          RECEIPT_STATUS = 0
	RECEIPT_STATUS_HALTED            RECEIPT_STATUS = 1
	RECEIPT_STATUS_THREW             RECEIPT_STATUS = 2
	RECEIPT_STATUS_TRANSACTION_ERROR RECEIPT_STATUS = -1
)

// Enum value maps for RECEIPT_STATUS.
var (
	RECEIPT_STATUS_name = map[int32]string{
		0:  "RETURNED",
		1:  "HALTED",
		2:  "THREW",
		-1: "TRANSACTION_ERROR",
	}
	RECEIPT_STATUS_value = map[string]int32{
		"RETURNED":          0,
		"HALTED":            1,
		"THREW":             2,
		"TRANSACTION_ERROR": -1,
	}
)

func (x RECEIPT_STATUS) Enum() *RECEIPT_STATUS {
	p := new(RECEIPT_STATUS)
	*p = x
	return p
}

func (x RECEIPT_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RECEIPT_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_receipt_proto_enumTypes[1].Descriptor()
}

func (RECEIPT_STATUS) Type() protoreflect.EnumType {
	return &file_receipt_proto_enumTypes[1]
}

func (x RECEIPT_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RECEIPT_STATUS.Descriptor instead.
func (RECEIPT_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{1}
}

type EXCEPTION int32

const (
	EXCEPTION_ERR_OUT_OF_GAS                 EXCEPTION = 0
	EXCEPTION_ERR_CODE_STORE_OUT_OF_GAS      EXCEPTION = 1
	EXCEPTION_ERR_DEPTH                      EXCEPTION = 2
	EXCEPTION_ERR_INSUFFICIENT_BALANCE       EXCEPTION = 3
	EXCEPTION_ERR_CONTRACT_ADDRESS_COLLISION EXCEPTION = 4
	EXCEPTION_ERR_EXECUTION_REVERTED         EXCEPTION = 5
	EXCEPTION_ERR_MAX_CODE_SIZE_EXCEEDED     EXCEPTION = 6
	EXCEPTION_ERR_INVALID_JUMP               EXCEPTION = 7
	EXCEPTION_ERR_WRITE_PROTECTION           EXCEPTION = 8
	EXCEPTION_ERR_RETURN_DATA_OUT_OF_BOUNDS  EXCEPTION = 9
	EXCEPTION_ERR_GAS_UINT_OVERFLOW          EXCEPTION = 10
	EXCEPTION_ERR_INVALID_CODE               EXCEPTION = 11
	EXCEPTION_ERR_NONCE_UINT_OVERFLOW        EXCEPTION = 12
	EXCEPTION_ERR_OUT_OF_BOUNDS              EXCEPTION = 13
	EXCEPTION_ERR_OVERFLOW                   EXCEPTION = 14
	EXCEPTION_ERR_ADDRESS_NOT_IN_RELATED     EXCEPTION = 15
	EXCEPTION_NONE                           EXCEPTION = -1
)

// Enum value maps for EXCEPTION.
var (
	EXCEPTION_name = map[int32]string{
		0:  "ERR_OUT_OF_GAS",
		1:  "ERR_CODE_STORE_OUT_OF_GAS",
		2:  "ERR_DEPTH",
		3:  "ERR_INSUFFICIENT_BALANCE",
		4:  "ERR_CONTRACT_ADDRESS_COLLISION",
		5:  "ERR_EXECUTION_REVERTED",
		6:  "ERR_MAX_CODE_SIZE_EXCEEDED",
		7:  "ERR_INVALID_JUMP",
		8:  "ERR_WRITE_PROTECTION",
		9:  "ERR_RETURN_DATA_OUT_OF_BOUNDS",
		10: "ERR_GAS_UINT_OVERFLOW",
		11: "ERR_INVALID_CODE",
		12: "ERR_NONCE_UINT_OVERFLOW",
		13: "ERR_OUT_OF_BOUNDS",
		14: "ERR_OVERFLOW",
		15: "ERR_ADDRESS_NOT_IN_RELATED",
		-1: "NONE",
	}
	EXCEPTION_value = map[string]int32{
		"ERR_OUT_OF_GAS":                 0,
		"ERR_CODE_STORE_OUT_OF_GAS":      1,
		"ERR_DEPTH":                      2,
		"ERR_INSUFFICIENT_BALANCE":       3,
		"ERR_CONTRACT_ADDRESS_COLLISION": 4,
		"ERR_EXECUTION_REVERTED":         5,
		"ERR_MAX_CODE_SIZE_EXCEEDED":     6,
		"ERR_INVALID_JUMP":               7,
		"ERR_WRITE_PROTECTION":           8,
		"ERR_RETURN_DATA_OUT_OF_BOUNDS":  9,
		"ERR_GAS_UINT_OVERFLOW":          10,
		"ERR_INVALID_CODE":               11,
		"ERR_NONCE_UINT_OVERFLOW":        12,
		"ERR_OUT_OF_BOUNDS":              13,
		"ERR_OVERFLOW":                   14,
		"ERR_ADDRESS_NOT_IN_RELATED":     15,
		"NONE":                           -1,
	}
)

func (x EXCEPTION) Enum() *EXCEPTION {
	p := new(EXCEPTION)
	*p = x
	return p
}

func (x EXCEPTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EXCEPTION) Descriptor() protoreflect.EnumDescriptor {
	return file_receipt_proto_enumTypes[2].Descriptor()
}

func (EXCEPTION) Type() protoreflect.EnumType {
	return &file_receipt_proto_enumTypes[2]
}

func (x EXCEPTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EXCEPTION.Descriptor instead.
func (EXCEPTION) EnumDescriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{2}
}

type Receipt struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	TransactionHash  []byte                  `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	FromAddress      []byte                  `protobuf:"bytes,2,opt,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	ToAddress        []byte                  `protobuf:"bytes,3,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Amount           []byte                  `protobuf:"bytes,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status           RECEIPT_STATUS          `protobuf:"varint,6,opt,name=Status,proto3,enum=receipt.RECEIPT_STATUS" json:"Status,omitempty"`
	Return           []byte                  `protobuf:"bytes,7,opt,name=Return,proto3" json:"Return,omitempty"`
	Exception        EXCEPTION               `protobuf:"varint,8,opt,name=Exception,proto3,enum=receipt.EXCEPTION" json:"Exception,omitempty"`
	GasUsed          uint64                  `protobuf:"varint,9,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	GasFee           uint64                  `protobuf:"varint,10,opt,name=GasFee,proto3" json:"GasFee,omitempty"`
	EventLogs        []*EventLog             `protobuf:"bytes,11,rep,name=EventLogs,proto3" json:"EventLogs,omitempty"`
	TransactionIndex uint64                  `protobuf:"varint,12,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	ProcessingType   RECEIPT_PROCESSING_TYPE `protobuf:"varint,13,opt,name=ProcessingType,proto3,enum=receipt.RECEIPT_PROCESSING_TYPE" json:"ProcessingType,omitempty"` // Thêm trường này
	RHash            []byte                  `protobuf:"bytes,14,opt,name=RHash,proto3" json:"RHash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *Receipt) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *Receipt) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *Receipt) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *Receipt) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Receipt) GetStatus() RECEIPT_STATUS {
	if x != nil {
		return x.Status
	}
	return RECEIPT_STATUS_RETURNED
}

func (x *Receipt) GetReturn() []byte {
	if x != nil {
		return x.Return
	}
	return nil
}

func (x *Receipt) GetException() EXCEPTION {
	if x != nil {
		return x.Exception
	}
	return EXCEPTION_ERR_OUT_OF_GAS
}

func (x *Receipt) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Receipt) GetGasFee() uint64 {
	if x != nil {
		return x.GasFee
	}
	return 0
}

func (x *Receipt) GetEventLogs() []*EventLog {
	if x != nil {
		return x.EventLogs
	}
	return nil
}

func (x *Receipt) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *Receipt) GetProcessingType() RECEIPT_PROCESSING_TYPE {
	if x != nil {
		return x.ProcessingType
	}
	return RECEIPT_PROCESSING_TYPE_POST_COMMIT_NOTIFICATION
}

func (x *Receipt) GetRHash() []byte {
	if x != nil {
		return x.RHash
	}
	return nil
}

type GetTransactionReceiptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash []byte                 `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"` // Hash của transaction cần lấy receipt
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionReceiptRequest) Reset() {
	*x = GetTransactionReceiptRequest{}
	mi := &file_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptRequest) ProtoMessage() {}

func (x *GetTransactionReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptRequest) Descriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionReceiptRequest) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

// GetTransactionReceiptResponse - Response chứa receipt data
type GetTransactionReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *RpcReceipt            `protobuf:"bytes,1,opt,name=Receipt,proto3" json:"Receipt,omitempty"` // RpcReceipt (null nếu không tìm thấy)
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`     // Error message nếu có lỗi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionReceiptResponse) Reset() {
	*x = GetTransactionReceiptResponse{}
	mi := &file_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptResponse) ProtoMessage() {}

func (x *GetTransactionReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptResponse) Descriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionReceiptResponse) GetReceipt() *RpcReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *GetTransactionReceiptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Receipts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*Receipt             `protobuf:"bytes,1,rep,name=Receipts,proto3" json:"Receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipts) Reset() {
	*x = Receipts{}
	mi := &file_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipts) ProtoMessage() {}

func (x *Receipts) ProtoReflect() protoreflect.Message {
	mi := &file_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipts.ProtoReflect.Descriptor instead.
func (*Receipts) Descriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *Receipts) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

var File_receipt_proto protoreflect.FileDescriptor

const file_receipt_proto_rawDesc = "" +
	"\n" +
	"\rreceipt.proto\x12\areceipt\x1a\x0fevent_log.proto\x1a\x11rpc_receipt.proto\"\xf7\x03\n" +
	"\aReceipt\x12(\n" +
	"\x0fTransactionHash\x18\x01 \x01(\fR\x0fTransactionHash\x12 \n" +
	"\vFromAddress\x18\x02 \x01(\fR\vFromAddress\x12\x1c\n" +
	"\tToAddress\x18\x03 \x01(\fR\tToAddress\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\fR\x06Amount\x12/\n" +
	"\x06Status\x18\x06 \x01(\x0e2\x17.receipt.RECEIPT_STATUSR\x06Status\x12\x16\n" +
	"\x06Return\x18\a \x01(\fR\x06Return\x120\n" +
	"\tException\x18\b \x01(\x0e2\x12.receipt.EXCEPTIONR\tException\x12\x18\n" +
	"\aGasUsed\x18\t \x01(\x04R\aGasUsed\x12\x16\n" +
	"\x06GasFee\x18\n" +
	" \x01(\x04R\x06GasFee\x121\n" +
	"\tEventLogs\x18\v \x03(\v2\x13.event_log.EventLogR\tEventLogs\x12*\n" +
	"\x10TransactionIndex\x18\f \x01(\x04R\x10TransactionIndex\x12H\n" +
	"\x0eProcessingType\x18\r \x01(\x0e2 .receipt.RECEIPT_PROCESSING_TYPER\x0eProcessingType\x12\x14\n" +
	"\x05RHash\x18\x0e \x01(\fR\x05RHash\"H\n" +
	"\x1cGetTransactionReceiptRequest\x12(\n" +
	"\x0fTransactionHash\x18\x01 \x01(\fR\x0fTransactionHash\"h\n" +
	"\x1dGetTransactionReceiptResponse\x121\n" +
	"\aReceipt\x18\x01 \x01(\v2\x17.rpc_request.RpcReceiptR\aReceipt\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"8\n" +
	"\bReceipts\x12,\n" +
	"\bReceipts\x18\x01 \x03(\v2\x10.receipt.ReceiptR\bReceipts*T\n" +
	"\x17RECEIPT_PROCESSING_TYPE\x12\x1c\n" +
	"\x18POST_COMMIT_NOTIFICATION\x10\x00\x12\x1b\n" +
	"\x17PRE_COMMIT_NOTIFICATION\x10\x01*U\n" +
	"\x0eRECEIPT_STATUS\x12\f\n" +
	"\bRETURNED\x10\x00\x12\n" +
	"\n" +
	"\x06HALTED\x10\x01\x12\t\n" +
	"\x05THREW\x10\x02\x12\x1e\n" +
	"\x11TRANSACTION_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\xc8\x03\n" +
	"\tEXCEPTION\x12\x12\n" +
	"\x0eERR_OUT_OF_GAS\x10\x00\x12\x1d\n" +
	"\x19ERR_CODE_STORE_OUT_OF_GAS\x10\x01\x12\r\n" +
	"\tERR_DEPTH\x10\x02\x12\x1c\n" +
	"\x18ERR_INSUFFICIENT_BALANCE\x10\x03\x12\"\n" +
	"\x1eERR_CONTRACT_ADDRESS_COLLISION\x10\x04\x12\x1a\n" +
	"\x16ERR_EXECUTION_REVERTED\x10\x05\x12\x1e\n" +
	"\x1aERR_MAX_CODE_SIZE_EXCEEDED\x10\x06\x12\x14\n" +
	"\x10ERR_INVALID_JUMP\x10\a\x12\x18\n" +
	"\x14ERR_WRITE_PROTECTION\x10\b\x12!\n" +
	"\x1dERR_RETURN_DATA_OUT_OF_BOUNDS\x10\t\x12\x19\n" +
	"\x15ERR_GAS_UINT_OVERFLOW\x10\n" +
	"\x12\x14\n" +
	"\x10ERR_INVALID_CODE\x10\v\x12\x1b\n" +
	"\x17ERR_NONCE_UINT_OVERFLOW\x10\f\x12\x15\n" +
	"\x11ERR_OUT_OF_BOUNDS\x10\r\x12\x10\n" +
	"\fERR_OVERFLOW\x10\x0e\x12\x1e\n" +
	"\x1aERR_ADDRESS_NOT_IN_RELATED\x10\x0f\x12\x11\n" +
	"\x04NONE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01B/\n" +
	"%com.meta_node.protos.compiled.receiptZ\x06/protob\x06proto3"

var (
	file_receipt_proto_rawDescOnce sync.Once
	file_receipt_proto_rawDescData []byte
)

func file_receipt_proto_rawDescGZIP() []byte {
	file_receipt_proto_rawDescOnce.Do(func() {
		file_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_receipt_proto_rawDesc), len(file_receipt_proto_rawDesc)))
	})
	return file_receipt_proto_rawDescData
}

var file_receipt_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_receipt_proto_goTypes = []any{
	(RECEIPT_PROCESSING_TYPE)(0),          // 0: receipt.RECEIPT_PROCESSING_TYPE
	(RECEIPT_STATUS)(0),                   // 1: receipt.RECEIPT_STATUS
	(EXCEPTION)(0),                        // 2: receipt.EXCEPTION
	(*Receipt)(nil),                       // 3: receipt.Receipt
	(*GetTransactionReceiptRequest)(nil),  // 4: receipt.GetTransactionReceiptRequest
	(*GetTransactionReceiptResponse)(nil), // 5: receipt.GetTransactionReceiptResponse
	(*Receipts)(nil),                      // 6: receipt.Receipts
	(*EventLog)(nil),                      // 7: event_log.EventLog
	(*RpcReceipt)(nil),                    // 8: rpc_request.RpcReceipt
}
var file_receipt_proto_depIdxs = []int32{
	1, // 0: receipt.Receipt.Status:type_name -> receipt.RECEIPT_STATUS
	2, // 1: receipt.Receipt.Exception:type_name -> receipt.EXCEPTION
	7, // 2: receipt.Receipt.EventLogs:type_name -> event_log.EventLog
	0, // 3: receipt.Receipt.ProcessingType:type_name -> receipt.RECEIPT_PROCESSING_TYPE
	8, // 4: receipt.GetTransactionReceiptResponse.Receipt:type_name -> rpc_request.RpcReceipt
	3, // 5: receipt.Receipts.Receipts:type_name -> receipt.Receipt
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_receipt_proto_init() }
func file_receipt_proto_init() {
	if File_receipt_proto != nil {
		return
	}
	file_event_log_proto_init()
	file_rpc_receipt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receipt_proto_rawDesc), len(file_receipt_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_receipt_proto_goTypes,
		DependencyIndexes: file_receipt_proto_depIdxs,
		EnumInfos:         file_receipt_proto_enumTypes,
		MessageInfos:      file_receipt_proto_msgTypes,
	}.Build()
	File_receipt_proto = out.File
	file_receipt_proto_goTypes = nil
	file_receipt_proto_depIdxs = nil
}
