// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: remote_storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum to define the database operation type
type OperationType int32

const (
	OperationType_UNDEFINED_OP    OperationType = 0 // Default value, should not be used
	OperationType_GET             OperationType = 1
	OperationType_PUT             OperationType = 2
	OperationType_DELETE          OperationType = 3
	OperationType_BATCH_PUT       OperationType = 4
	OperationType_BATCH_DELETE    OperationType = 5
	OperationType_GET_BACKUP_PATH OperationType = 6
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "UNDEFINED_OP",
		1: "GET",
		2: "PUT",
		3: "DELETE",
		4: "BATCH_PUT",
		5: "BATCH_DELETE",
		6: "GET_BACKUP_PATH",
	}
	OperationType_value = map[string]int32{
		"UNDEFINED_OP":    0,
		"GET":             1,
		"PUT":             2,
		"DELETE":          3,
		"BATCH_PUT":       4,
		"BATCH_DELETE":    5,
		"GET_BACKUP_PATH": 6,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_storage_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_remote_storage_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{0}
}

// Get Operation
type StorageGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetRequest) Reset() {
	*x = StorageGetRequest{}
	mi := &file_remote_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetRequest) ProtoMessage() {}

func (x *StorageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetRequest.ProtoReflect.Descriptor instead.
func (*StorageGetRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StorageGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type StorageGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetResponse) Reset() {
	*x = StorageGetResponse{}
	mi := &file_remote_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetResponse) ProtoMessage() {}

func (x *StorageGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetResponse.ProtoReflect.Descriptor instead.
func (*StorageGetResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StorageGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Put Operation
type StoragePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePutRequest) Reset() {
	*x = StoragePutRequest{}
	mi := &file_remote_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePutRequest) ProtoMessage() {}

func (x *StoragePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePutRequest.ProtoReflect.Descriptor instead.
func (*StoragePutRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoragePutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoragePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoragePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePutResponse) Reset() {
	*x = StoragePutResponse{}
	mi := &file_remote_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePutResponse) ProtoMessage() {}

func (x *StoragePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePutResponse.ProtoReflect.Descriptor instead.
func (*StoragePutResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StoragePutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Delete Operation
type StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_remote_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{4}
}

func (x *StorageDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_remote_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{5}
}

func (x *StorageDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchPut Operation
type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_remote_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValuePair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StorageBatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KeyValuePair        `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchPutRequest) Reset() {
	*x = StorageBatchPutRequest{}
	mi := &file_remote_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchPutRequest) ProtoMessage() {}

func (x *StorageBatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchPutRequest.ProtoReflect.Descriptor instead.
func (*StorageBatchPutRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{7}
}

func (x *StorageBatchPutRequest) GetKvs() []*KeyValuePair {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type StorageBatchPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchPutResponse) Reset() {
	*x = StorageBatchPutResponse{}
	mi := &file_remote_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchPutResponse) ProtoMessage() {}

func (x *StorageBatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchPutResponse.ProtoReflect.Descriptor instead.
func (*StorageBatchPutResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{8}
}

func (x *StorageBatchPutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchDelete Operation
type StorageBatchDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchDeleteRequest) Reset() {
	*x = StorageBatchDeleteRequest{}
	mi := &file_remote_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchDeleteRequest) ProtoMessage() {}

func (x *StorageBatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{9}
}

func (x *StorageBatchDeleteRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type StorageBatchDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchDeleteResponse) Reset() {
	*x = StorageBatchDeleteResponse{}
	mi := &file_remote_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchDeleteResponse) ProtoMessage() {}

func (x *StorageBatchDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageBatchDeleteResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{10}
}

func (x *StorageBatchDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetBackupPath Operation
type StorageGetBackupPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetBackupPathRequest) Reset() {
	*x = StorageGetBackupPathRequest{}
	mi := &file_remote_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetBackupPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetBackupPathRequest) ProtoMessage() {}

func (x *StorageGetBackupPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetBackupPathRequest.ProtoReflect.Descriptor instead.
func (*StorageGetBackupPathRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{11}
}

type StorageGetBackupPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error field, empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetBackupPathResponse) Reset() {
	*x = StorageGetBackupPathResponse{}
	mi := &file_remote_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetBackupPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetBackupPathResponse) ProtoMessage() {}

func (x *StorageGetBackupPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetBackupPathResponse.ProtoReflect.Descriptor instead.
func (*StorageGetBackupPathResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{12}
}

func (x *StorageGetBackupPathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageGetBackupPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Wrapper for all DB requests
type DatabaseOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType OperationType          `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=remote_storage.OperationType" json:"operation_type,omitempty"` // Operation type
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                // ID of this request (optional, useful for tracking)
	// Types that are valid to be assigned to Payload:
	//
	//	*DatabaseOperationRequest_GetRequest
	//	*DatabaseOperationRequest_PutRequest
	//	*DatabaseOperationRequest_DeleteRequest
	//	*DatabaseOperationRequest_BatchPutRequest
	//	*DatabaseOperationRequest_BatchDeleteRequest
	//	*DatabaseOperationRequest_GetBackupPathRequest
	Payload       isDatabaseOperationRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseOperationRequest) Reset() {
	*x = DatabaseOperationRequest{}
	mi := &file_remote_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseOperationRequest) ProtoMessage() {}

func (x *DatabaseOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseOperationRequest.ProtoReflect.Descriptor instead.
func (*DatabaseOperationRequest) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{13}
}

func (x *DatabaseOperationRequest) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_UNDEFINED_OP
}

func (x *DatabaseOperationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DatabaseOperationRequest) GetPayload() isDatabaseOperationRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DatabaseOperationRequest) GetGetRequest() *StorageGetRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_GetRequest); ok {
			return x.GetRequest
		}
	}
	return nil
}

func (x *DatabaseOperationRequest) GetPutRequest() *StoragePutRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_PutRequest); ok {
			return x.PutRequest
		}
	}
	return nil
}

func (x *DatabaseOperationRequest) GetDeleteRequest() *StorageDeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *DatabaseOperationRequest) GetBatchPutRequest() *StorageBatchPutRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_BatchPutRequest); ok {
			return x.BatchPutRequest
		}
	}
	return nil
}

func (x *DatabaseOperationRequest) GetBatchDeleteRequest() *StorageBatchDeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_BatchDeleteRequest); ok {
			return x.BatchDeleteRequest
		}
	}
	return nil
}

func (x *DatabaseOperationRequest) GetGetBackupPathRequest() *StorageGetBackupPathRequest {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationRequest_GetBackupPathRequest); ok {
			return x.GetBackupPathRequest
		}
	}
	return nil
}

type isDatabaseOperationRequest_Payload interface {
	isDatabaseOperationRequest_Payload()
}

type DatabaseOperationRequest_GetRequest struct {
	GetRequest *StorageGetRequest `protobuf:"bytes,3,opt,name=get_request,json=getRequest,proto3,oneof"`
}

type DatabaseOperationRequest_PutRequest struct {
	PutRequest *StoragePutRequest `protobuf:"bytes,4,opt,name=put_request,json=putRequest,proto3,oneof"`
}

type DatabaseOperationRequest_DeleteRequest struct {
	DeleteRequest *StorageDeleteRequest `protobuf:"bytes,5,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type DatabaseOperationRequest_BatchPutRequest struct {
	BatchPutRequest *StorageBatchPutRequest `protobuf:"bytes,6,opt,name=batch_put_request,json=batchPutRequest,proto3,oneof"`
}

type DatabaseOperationRequest_BatchDeleteRequest struct {
	BatchDeleteRequest *StorageBatchDeleteRequest `protobuf:"bytes,7,opt,name=batch_delete_request,json=batchDeleteRequest,proto3,oneof"`
}

type DatabaseOperationRequest_GetBackupPathRequest struct {
	GetBackupPathRequest *StorageGetBackupPathRequest `protobuf:"bytes,8,opt,name=get_backup_path_request,json=getBackupPathRequest,proto3,oneof"`
}

func (*DatabaseOperationRequest_GetRequest) isDatabaseOperationRequest_Payload() {}

func (*DatabaseOperationRequest_PutRequest) isDatabaseOperationRequest_Payload() {}

func (*DatabaseOperationRequest_DeleteRequest) isDatabaseOperationRequest_Payload() {}

func (*DatabaseOperationRequest_BatchPutRequest) isDatabaseOperationRequest_Payload() {}

func (*DatabaseOperationRequest_BatchDeleteRequest) isDatabaseOperationRequest_Payload() {}

func (*DatabaseOperationRequest_GetBackupPathRequest) isDatabaseOperationRequest_Payload() {}

// Wrapper for all DB responses
type DatabaseOperationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OriginalOperationType OperationType          `protobuf:"varint,1,opt,name=original_operation_type,json=originalOperationType,proto3,enum=remote_storage.OperationType" json:"original_operation_type,omitempty"` // Original operation type this response is for
	RequestId             string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                                          // ID of the original request (for client to map response to request)
	Error                 string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                                                                   // General error field for the entire operation, or error at the wrapper level.
	// If empty, check for error in the specific payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*DatabaseOperationResponse_GetResponse
	//	*DatabaseOperationResponse_PutResponse
	//	*DatabaseOperationResponse_DeleteResponse
	//	*DatabaseOperationResponse_BatchPutResponse
	//	*DatabaseOperationResponse_BatchDeleteResponse
	//	*DatabaseOperationResponse_GetBackupPathResponse
	Payload       isDatabaseOperationResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseOperationResponse) Reset() {
	*x = DatabaseOperationResponse{}
	mi := &file_remote_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseOperationResponse) ProtoMessage() {}

func (x *DatabaseOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseOperationResponse.ProtoReflect.Descriptor instead.
func (*DatabaseOperationResponse) Descriptor() ([]byte, []int) {
	return file_remote_storage_proto_rawDescGZIP(), []int{14}
}

func (x *DatabaseOperationResponse) GetOriginalOperationType() OperationType {
	if x != nil {
		return x.OriginalOperationType
	}
	return OperationType_UNDEFINED_OP
}

func (x *DatabaseOperationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DatabaseOperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DatabaseOperationResponse) GetPayload() isDatabaseOperationResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DatabaseOperationResponse) GetGetResponse() *StorageGetResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_GetResponse); ok {
			return x.GetResponse
		}
	}
	return nil
}

func (x *DatabaseOperationResponse) GetPutResponse() *StoragePutResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_PutResponse); ok {
			return x.PutResponse
		}
	}
	return nil
}

func (x *DatabaseOperationResponse) GetDeleteResponse() *StorageDeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *DatabaseOperationResponse) GetBatchPutResponse() *StorageBatchPutResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_BatchPutResponse); ok {
			return x.BatchPutResponse
		}
	}
	return nil
}

func (x *DatabaseOperationResponse) GetBatchDeleteResponse() *StorageBatchDeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_BatchDeleteResponse); ok {
			return x.BatchDeleteResponse
		}
	}
	return nil
}

func (x *DatabaseOperationResponse) GetGetBackupPathResponse() *StorageGetBackupPathResponse {
	if x != nil {
		if x, ok := x.Payload.(*DatabaseOperationResponse_GetBackupPathResponse); ok {
			return x.GetBackupPathResponse
		}
	}
	return nil
}

type isDatabaseOperationResponse_Payload interface {
	isDatabaseOperationResponse_Payload()
}

type DatabaseOperationResponse_GetResponse struct {
	GetResponse *StorageGetResponse `protobuf:"bytes,4,opt,name=get_response,json=getResponse,proto3,oneof"`
}

type DatabaseOperationResponse_PutResponse struct {
	PutResponse *StoragePutResponse `protobuf:"bytes,5,opt,name=put_response,json=putResponse,proto3,oneof"`
}

type DatabaseOperationResponse_DeleteResponse struct {
	DeleteResponse *StorageDeleteResponse `protobuf:"bytes,6,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type DatabaseOperationResponse_BatchPutResponse struct {
	BatchPutResponse *StorageBatchPutResponse `protobuf:"bytes,7,opt,name=batch_put_response,json=batchPutResponse,proto3,oneof"`
}

type DatabaseOperationResponse_BatchDeleteResponse struct {
	BatchDeleteResponse *StorageBatchDeleteResponse `protobuf:"bytes,8,opt,name=batch_delete_response,json=batchDeleteResponse,proto3,oneof"`
}

type DatabaseOperationResponse_GetBackupPathResponse struct {
	GetBackupPathResponse *StorageGetBackupPathResponse `protobuf:"bytes,9,opt,name=get_backup_path_response,json=getBackupPathResponse,proto3,oneof"`
}

func (*DatabaseOperationResponse_GetResponse) isDatabaseOperationResponse_Payload() {}

func (*DatabaseOperationResponse_PutResponse) isDatabaseOperationResponse_Payload() {}

func (*DatabaseOperationResponse_DeleteResponse) isDatabaseOperationResponse_Payload() {}

func (*DatabaseOperationResponse_BatchPutResponse) isDatabaseOperationResponse_Payload() {}

func (*DatabaseOperationResponse_BatchDeleteResponse) isDatabaseOperationResponse_Payload() {}

func (*DatabaseOperationResponse_GetBackupPathResponse) isDatabaseOperationResponse_Payload() {}

var File_remote_storage_proto protoreflect.FileDescriptor

const file_remote_storage_proto_rawDesc = "" +
	"\n" +
	"\x14remote_storage.proto\x12\x0eremote_storage\"%\n" +
	"\x11StorageGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"@\n" +
	"\x12StorageGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\";\n" +
	"\x11StoragePutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"*\n" +
	"\x12StoragePutResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"(\n" +
	"\x14StorageDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"-\n" +
	"\x15StorageDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"H\n" +
	"\x16StorageBatchPutRequest\x12.\n" +
	"\x03kvs\x18\x01 \x03(\v2\x1c.remote_storage.KeyValuePairR\x03kvs\"/\n" +
	"\x17StorageBatchPutResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"/\n" +
	"\x19StorageBatchDeleteRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\"2\n" +
	"\x1aStorageBatchDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x1d\n" +
	"\x1bStorageGetBackupPathRequest\"H\n" +
	"\x1cStorageGetBackupPathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x05\n" +
	"\x18DatabaseOperationRequest\x12D\n" +
	"\x0eoperation_type\x18\x01 \x01(\x0e2\x1d.remote_storage.OperationTypeR\roperationType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12D\n" +
	"\vget_request\x18\x03 \x01(\v2!.remote_storage.StorageGetRequestH\x00R\n" +
	"getRequest\x12D\n" +
	"\vput_request\x18\x04 \x01(\v2!.remote_storage.StoragePutRequestH\x00R\n" +
	"putRequest\x12M\n" +
	"\x0edelete_request\x18\x05 \x01(\v2$.remote_storage.StorageDeleteRequestH\x00R\rdeleteRequest\x12T\n" +
	"\x11batch_put_request\x18\x06 \x01(\v2&.remote_storage.StorageBatchPutRequestH\x00R\x0fbatchPutRequest\x12]\n" +
	"\x14batch_delete_request\x18\a \x01(\v2).remote_storage.StorageBatchDeleteRequestH\x00R\x12batchDeleteRequest\x12d\n" +
	"\x17get_backup_path_request\x18\b \x01(\v2+.remote_storage.StorageGetBackupPathRequestH\x00R\x14getBackupPathRequestB\t\n" +
	"\apayload\"\xba\x05\n" +
	"\x19DatabaseOperationResponse\x12U\n" +
	"\x17original_operation_type\x18\x01 \x01(\x0e2\x1d.remote_storage.OperationTypeR\x15originalOperationType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12G\n" +
	"\fget_response\x18\x04 \x01(\v2\".remote_storage.StorageGetResponseH\x00R\vgetResponse\x12G\n" +
	"\fput_response\x18\x05 \x01(\v2\".remote_storage.StoragePutResponseH\x00R\vputResponse\x12P\n" +
	"\x0fdelete_response\x18\x06 \x01(\v2%.remote_storage.StorageDeleteResponseH\x00R\x0edeleteResponse\x12W\n" +
	"\x12batch_put_response\x18\a \x01(\v2'.remote_storage.StorageBatchPutResponseH\x00R\x10batchPutResponse\x12`\n" +
	"\x15batch_delete_response\x18\b \x01(\v2*.remote_storage.StorageBatchDeleteResponseH\x00R\x13batchDeleteResponse\x12g\n" +
	"\x18get_backup_path_response\x18\t \x01(\v2,.remote_storage.StorageGetBackupPathResponseH\x00R\x15getBackupPathResponseB\t\n" +
	"\apayload*u\n" +
	"\rOperationType\x12\x10\n" +
	"\fUNDEFINED_OP\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\r\n" +
	"\tBATCH_PUT\x10\x04\x12\x10\n" +
	"\fBATCH_DELETE\x10\x05\x12\x13\n" +
	"\x0fGET_BACKUP_PATH\x10\x06B0\n" +
	"&com.meta_node.protos.compiled.messagesZ\x06/protob\x06proto3"

var (
	file_remote_storage_proto_rawDescOnce sync.Once
	file_remote_storage_proto_rawDescData []byte
)

func file_remote_storage_proto_rawDescGZIP() []byte {
	file_remote_storage_proto_rawDescOnce.Do(func() {
		file_remote_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_storage_proto_rawDesc), len(file_remote_storage_proto_rawDesc)))
	})
	return file_remote_storage_proto_rawDescData
}

var file_remote_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_remote_storage_proto_goTypes = []any{
	(OperationType)(0),                   // 0: remote_storage.OperationType
	(*StorageGetRequest)(nil),            // 1: remote_storage.StorageGetRequest
	(*StorageGetResponse)(nil),           // 2: remote_storage.StorageGetResponse
	(*StoragePutRequest)(nil),            // 3: remote_storage.StoragePutRequest
	(*StoragePutResponse)(nil),           // 4: remote_storage.StoragePutResponse
	(*StorageDeleteRequest)(nil),         // 5: remote_storage.StorageDeleteRequest
	(*StorageDeleteResponse)(nil),        // 6: remote_storage.StorageDeleteResponse
	(*KeyValuePair)(nil),                 // 7: remote_storage.KeyValuePair
	(*StorageBatchPutRequest)(nil),       // 8: remote_storage.StorageBatchPutRequest
	(*StorageBatchPutResponse)(nil),      // 9: remote_storage.StorageBatchPutResponse
	(*StorageBatchDeleteRequest)(nil),    // 10: remote_storage.StorageBatchDeleteRequest
	(*StorageBatchDeleteResponse)(nil),   // 11: remote_storage.StorageBatchDeleteResponse
	(*StorageGetBackupPathRequest)(nil),  // 12: remote_storage.StorageGetBackupPathRequest
	(*StorageGetBackupPathResponse)(nil), // 13: remote_storage.StorageGetBackupPathResponse
	(*DatabaseOperationRequest)(nil),     // 14: remote_storage.DatabaseOperationRequest
	(*DatabaseOperationResponse)(nil),    // 15: remote_storage.DatabaseOperationResponse
}
var file_remote_storage_proto_depIdxs = []int32{
	7,  // 0: remote_storage.StorageBatchPutRequest.kvs:type_name -> remote_storage.KeyValuePair
	0,  // 1: remote_storage.DatabaseOperationRequest.operation_type:type_name -> remote_storage.OperationType
	1,  // 2: remote_storage.DatabaseOperationRequest.get_request:type_name -> remote_storage.StorageGetRequest
	3,  // 3: remote_storage.DatabaseOperationRequest.put_request:type_name -> remote_storage.StoragePutRequest
	5,  // 4: remote_storage.DatabaseOperationRequest.delete_request:type_name -> remote_storage.StorageDeleteRequest
	8,  // 5: remote_storage.DatabaseOperationRequest.batch_put_request:type_name -> remote_storage.StorageBatchPutRequest
	10, // 6: remote_storage.DatabaseOperationRequest.batch_delete_request:type_name -> remote_storage.StorageBatchDeleteRequest
	12, // 7: remote_storage.DatabaseOperationRequest.get_backup_path_request:type_name -> remote_storage.StorageGetBackupPathRequest
	0,  // 8: remote_storage.DatabaseOperationResponse.original_operation_type:type_name -> remote_storage.OperationType
	2,  // 9: remote_storage.DatabaseOperationResponse.get_response:type_name -> remote_storage.StorageGetResponse
	4,  // 10: remote_storage.DatabaseOperationResponse.put_response:type_name -> remote_storage.StoragePutResponse
	6,  // 11: remote_storage.DatabaseOperationResponse.delete_response:type_name -> remote_storage.StorageDeleteResponse
	9,  // 12: remote_storage.DatabaseOperationResponse.batch_put_response:type_name -> remote_storage.StorageBatchPutResponse
	11, // 13: remote_storage.DatabaseOperationResponse.batch_delete_response:type_name -> remote_storage.StorageBatchDeleteResponse
	13, // 14: remote_storage.DatabaseOperationResponse.get_backup_path_response:type_name -> remote_storage.StorageGetBackupPathResponse
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_remote_storage_proto_init() }
func file_remote_storage_proto_init() {
	if File_remote_storage_proto != nil {
		return
	}
	file_remote_storage_proto_msgTypes[13].OneofWrappers = []any{
		(*DatabaseOperationRequest_GetRequest)(nil),
		(*DatabaseOperationRequest_PutRequest)(nil),
		(*DatabaseOperationRequest_DeleteRequest)(nil),
		(*DatabaseOperationRequest_BatchPutRequest)(nil),
		(*DatabaseOperationRequest_BatchDeleteRequest)(nil),
		(*DatabaseOperationRequest_GetBackupPathRequest)(nil),
	}
	file_remote_storage_proto_msgTypes[14].OneofWrappers = []any{
		(*DatabaseOperationResponse_GetResponse)(nil),
		(*DatabaseOperationResponse_PutResponse)(nil),
		(*DatabaseOperationResponse_DeleteResponse)(nil),
		(*DatabaseOperationResponse_BatchPutResponse)(nil),
		(*DatabaseOperationResponse_BatchDeleteResponse)(nil),
		(*DatabaseOperationResponse_GetBackupPathResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_storage_proto_rawDesc), len(file_remote_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_storage_proto_goTypes,
		DependencyIndexes: file_remote_storage_proto_depIdxs,
		EnumInfos:         file_remote_storage_proto_enumTypes,
		MessageInfos:      file_remote_storage_proto_msgTypes,
	}.Build()
	File_remote_storage_proto = out.File
	file_remote_storage_proto_goTypes = nil
	file_remote_storage_proto_depIdxs = nil
}
