// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: robot_tx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoredErrorData lưu thông tin lỗi từ dispatch và processTransactionQueue
type StoredErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                   // Transaction hash (hex string) - dùng làm key
	InputData     string                 `protobuf:"bytes,2,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`          // Input data từ dispatch (serialized as JSON string)
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Mã lỗi hoặc thông báo lỗi
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredErrorData) Reset() {
	*x = StoredErrorData{}
	mi := &file_robot_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredErrorData) ProtoMessage() {}

func (x *StoredErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_robot_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredErrorData.ProtoReflect.Descriptor instead.
func (*StoredErrorData) Descriptor() ([]byte, []int) {
	return file_robot_tx_proto_rawDescGZIP(), []int{0}
}

func (x *StoredErrorData) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *StoredErrorData) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *StoredErrorData) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StoredErrorData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_robot_tx_proto protoreflect.FileDescriptor

const file_robot_tx_proto_rawDesc = "" +
	"\n" +
	"\x0erobot_tx.proto\x12\x05proto\"\x8d\x01\n" +
	"\x0fStoredErrorData\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"input_data\x18\x02 \x01(\tR\tinputData\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAtB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_robot_tx_proto_rawDescOnce sync.Once
	file_robot_tx_proto_rawDescData []byte
)

func file_robot_tx_proto_rawDescGZIP() []byte {
	file_robot_tx_proto_rawDescOnce.Do(func() {
		file_robot_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robot_tx_proto_rawDesc), len(file_robot_tx_proto_rawDesc)))
	})
	return file_robot_tx_proto_rawDescData
}

var file_robot_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_robot_tx_proto_goTypes = []any{
	(*StoredErrorData)(nil), // 0: proto.StoredErrorData
}
var file_robot_tx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_robot_tx_proto_init() }
func file_robot_tx_proto_init() {
	if File_robot_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robot_tx_proto_rawDesc), len(file_robot_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_robot_tx_proto_goTypes,
		DependencyIndexes: file_robot_tx_proto_depIdxs,
		MessageInfos:      file_robot_tx_proto_msgTypes,
	}.Build()
	File_robot_tx_proto = out.File
	file_robot_tx_proto_goTypes = nil
	file_robot_tx_proto_depIdxs = nil
}
