// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_receipt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcLogEntry - Log entry dùng chung cho cả Event và Receipt
// Tất cả fields dùng string để khớp với chain JSON output (hex format)
type RpcLogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`                   // Contract address
	Topics           []string               `protobuf:"bytes,2,rep,name=Topics,proto3" json:"Topics,omitempty"`                     // Topics (event signature + indexed params)
	Data             string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`                         // Non-indexed event data (hex)
	BlockNumber      string                 `protobuf:"bytes,4,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`           // Block number (hex)
	TransactionHash  string                 `protobuf:"bytes,5,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`   // Transaction hash
	BlockHash        string                 `protobuf:"bytes,6,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`               // Block hash
	TransactionIndex string                 `protobuf:"bytes,7,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"` // Transaction index (hex)
	LogIndex         string                 `protobuf:"bytes,8,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`                 // Log index (hex)
	Removed          bool                   `protobuf:"varint,9,opt,name=Removed,proto3" json:"Removed,omitempty"`                  // Removed flag (reorg)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RpcLogEntry) Reset() {
	*x = RpcLogEntry{}
	mi := &file_rpc_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcLogEntry) ProtoMessage() {}

func (x *RpcLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcLogEntry.ProtoReflect.Descriptor instead.
func (*RpcLogEntry) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *RpcLogEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RpcLogEntry) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *RpcLogEntry) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RpcLogEntry) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcLogEntry) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcLogEntry) GetLogIndex() string {
	if x != nil {
		return x.LogIndex
	}
	return ""
}

func (x *RpcLogEntry) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// RpcEvent - Subscription event notification = subscription_id + log entry
type RpcEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=SubscriptionId,proto3" json:"SubscriptionId,omitempty"` // Subscription ID (0xabc...)
	Log            *RpcLogEntry           `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`                       // Log entry data
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RpcEvent) Reset() {
	*x = RpcEvent{}
	mi := &file_rpc_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEvent) ProtoMessage() {}

func (x *RpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEvent.ProtoReflect.Descriptor instead.
func (*RpcEvent) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *RpcEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RpcEvent) GetLog() *RpcLogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

// RpcReceipt - Transaction receipt gửi qua TCP (pure protobuf)
type RpcReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash   string                 `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	From              string                 `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                string                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	ContractAddress   string                 `protobuf:"bytes,4,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"` // Nếu deploy contract
	Status            string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`                   // "0x1" = success, "0x0" = fail
	GasUsed           string                 `protobuf:"bytes,6,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`                 // Hex string
	CumulativeGasUsed string                 `protobuf:"bytes,7,opt,name=CumulativeGasUsed,proto3" json:"CumulativeGasUsed,omitempty"`
	EffectiveGasPrice string                 `protobuf:"bytes,8,opt,name=EffectiveGasPrice,proto3" json:"EffectiveGasPrice,omitempty"`
	BlockHash         string                 `protobuf:"bytes,9,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockNumber       string                 `protobuf:"bytes,10,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"` // Hex string
	TransactionIndex  string                 `protobuf:"bytes,11,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	Type              string                 `protobuf:"bytes,12,opt,name=Type,proto3" json:"Type,omitempty"` // Transaction type
	Logs              []*RpcLogEntry         `protobuf:"bytes,13,rep,name=Logs,proto3" json:"Logs,omitempty"` // Dùng chung RpcLogEntry
	LogsBloom         string                 `protobuf:"bytes,14,opt,name=LogsBloom,proto3" json:"LogsBloom,omitempty"`
	ReturnData        []byte                 `protobuf:"bytes,15,opt,name=ReturnData,proto3" json:"ReturnData,omitempty"` // Return data từ EVM execution
	Exception         string                 `protobuf:"bytes,16,opt,name=Exception,proto3" json:"Exception,omitempty"`   // Exception type nếu có lỗi
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RpcReceipt) Reset() {
	*x = RpcReceipt{}
	mi := &file_rpc_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReceipt) ProtoMessage() {}

func (x *RpcReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReceipt.ProtoReflect.Descriptor instead.
func (*RpcReceipt) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *RpcReceipt) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcReceipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RpcReceipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RpcReceipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RpcReceipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RpcReceipt) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *RpcReceipt) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *RpcReceipt) GetEffectiveGasPrice() string {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return ""
}

func (x *RpcReceipt) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcReceipt) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcReceipt) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcReceipt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RpcReceipt) GetLogs() []*RpcLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *RpcReceipt) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

func (x *RpcReceipt) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *RpcReceipt) GetException() string {
	if x != nil {
		return x.Exception
	}
	return ""
}

var File_rpc_receipt_proto protoreflect.FileDescriptor

const file_rpc_receipt_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_receipt.proto\x12\vrpc_request\"\x9f\x02\n" +
	"\vRpcLogEntry\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x16\n" +
	"\x06Topics\x18\x02 \x03(\tR\x06Topics\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data\x12 \n" +
	"\vBlockNumber\x18\x04 \x01(\tR\vBlockNumber\x12(\n" +
	"\x0fTransactionHash\x18\x05 \x01(\tR\x0fTransactionHash\x12\x1c\n" +
	"\tBlockHash\x18\x06 \x01(\tR\tBlockHash\x12*\n" +
	"\x10TransactionIndex\x18\a \x01(\tR\x10TransactionIndex\x12\x1a\n" +
	"\bLogIndex\x18\b \x01(\tR\bLogIndex\x12\x18\n" +
	"\aRemoved\x18\t \x01(\bR\aRemoved\"^\n" +
	"\bRpcEvent\x12&\n" +
	"\x0eSubscriptionId\x18\x01 \x01(\tR\x0eSubscriptionId\x12*\n" +
	"\x03Log\x18\x02 \x01(\v2\x18.rpc_request.RpcLogEntryR\x03Log\"\x9c\x04\n" +
	"\n" +
	"RpcReceipt\x12(\n" +
	"\x0fTransactionHash\x18\x01 \x01(\tR\x0fTransactionHash\x12\x12\n" +
	"\x04From\x18\x02 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\tR\x02To\x12(\n" +
	"\x0fContractAddress\x18\x04 \x01(\tR\x0fContractAddress\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\x12\x18\n" +
	"\aGasUsed\x18\x06 \x01(\tR\aGasUsed\x12,\n" +
	"\x11CumulativeGasUsed\x18\a \x01(\tR\x11CumulativeGasUsed\x12,\n" +
	"\x11EffectiveGasPrice\x18\b \x01(\tR\x11EffectiveGasPrice\x12\x1c\n" +
	"\tBlockHash\x18\t \x01(\tR\tBlockHash\x12 \n" +
	"\vBlockNumber\x18\n" +
	" \x01(\tR\vBlockNumber\x12*\n" +
	"\x10TransactionIndex\x18\v \x01(\tR\x10TransactionIndex\x12\x12\n" +
	"\x04Type\x18\f \x01(\tR\x04Type\x12,\n" +
	"\x04Logs\x18\r \x03(\v2\x18.rpc_request.RpcLogEntryR\x04Logs\x12\x1c\n" +
	"\tLogsBloom\x18\x0e \x01(\tR\tLogsBloom\x12\x1e\n" +
	"\n" +
	"ReturnData\x18\x0f \x01(\fR\n" +
	"ReturnData\x12\x1c\n" +
	"\tException\x18\x10 \x01(\tR\tExceptionB\bZ\x06/protob\x06proto3"

var (
	file_rpc_receipt_proto_rawDescOnce sync.Once
	file_rpc_receipt_proto_rawDescData []byte
)

func file_rpc_receipt_proto_rawDescGZIP() []byte {
	file_rpc_receipt_proto_rawDescOnce.Do(func() {
		file_rpc_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_receipt_proto_rawDesc), len(file_rpc_receipt_proto_rawDesc)))
	})
	return file_rpc_receipt_proto_rawDescData
}

var file_rpc_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_receipt_proto_goTypes = []any{
	(*RpcLogEntry)(nil), // 0: rpc_request.RpcLogEntry
	(*RpcEvent)(nil),    // 1: rpc_request.RpcEvent
	(*RpcReceipt)(nil),  // 2: rpc_request.RpcReceipt
}
var file_rpc_receipt_proto_depIdxs = []int32{
	0, // 0: rpc_request.RpcEvent.Log:type_name -> rpc_request.RpcLogEntry
	0, // 1: rpc_request.RpcReceipt.Logs:type_name -> rpc_request.RpcLogEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_receipt_proto_init() }
func file_rpc_receipt_proto_init() {
	if File_rpc_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_receipt_proto_rawDesc), len(file_rpc_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_receipt_proto_goTypes,
		DependencyIndexes: file_rpc_receipt_proto_depIdxs,
		MessageInfos:      file_rpc_receipt_proto_msgTypes,
	}.Build()
	File_rpc_receipt_proto = out.File
	file_rpc_receipt_proto_goTypes = nil
	file_rpc_receipt_proto_depIdxs = nil
}
