// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcRequest đại diện cho một JSON-RPC request gửi qua TCP
type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"` // "2.0"
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // e.g. "net_version", "eth_call", "eth_sendRawTransaction"
	Params        [][]byte               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`   // Params dạng bytes (mỗi param được JSON encode)
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`           // Request ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_rpc_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetParams() [][]byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RpcResponse đại diện cho một JSON-RPC response trả về qua TCP
type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"` // "2.0"
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`   // Result dạng bytes (JSON encoded)
	Error         *RpcError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // Error nếu có
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`           // Request ID tương ứng
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_rpc_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *RpcResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RpcResponse) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RpcResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RpcError đại diện cho lỗi trong JSON-RPC
type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_rpc_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{2}
}

func (x *RpcError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcError) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// TcpSendTxRequest - request gửi raw transaction qua TCP dạng binary (không JSON)
// Client gửi raw eth tx bytes trực tiếp, không cần hex encode → nhanh hơn
type TcpSendTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawTx         []byte                 `protobuf:"bytes,1,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"` // raw ethereum tx bytes (đã decode từ hex)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpSendTxRequest) Reset() {
	*x = TcpSendTxRequest{}
	mi := &file_rpc_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpSendTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpSendTxRequest) ProtoMessage() {}

func (x *TcpSendTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpSendTxRequest.ProtoReflect.Descriptor instead.
func (*TcpSendTxRequest) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{3}
}

func (x *TcpSendTxRequest) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

// TcpEthCallRequest - request eth_call qua TCP dạng binary
type TcpEthCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []byte                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`     // contract address (20 bytes)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // ABI-encoded function call data (raw bytes, không hex)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpEthCallRequest) Reset() {
	*x = TcpEthCallRequest{}
	mi := &file_rpc_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpEthCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpEthCallRequest) ProtoMessage() {}

func (x *TcpEthCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpEthCallRequest.ProtoReflect.Descriptor instead.
func (*TcpEthCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{4}
}

func (x *TcpEthCallRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TcpEthCallRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TcpAddressParam - param chung chứa 1 address (20 bytes)
type TcpAddressParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpAddressParam) Reset() {
	*x = TcpAddressParam{}
	mi := &file_rpc_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpAddressParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpAddressParam) ProtoMessage() {}

func (x *TcpAddressParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpAddressParam.ProtoReflect.Descriptor instead.
func (*TcpAddressParam) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{5}
}

func (x *TcpAddressParam) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// TcpHashParam - param chung chứa 1 hash (32 bytes)
type TcpHashParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpHashParam) Reset() {
	*x = TcpHashParam{}
	mi := &file_rpc_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpHashParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpHashParam) ProtoMessage() {}

func (x *TcpHashParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpHashParam.ProtoReflect.Descriptor instead.
func (*TcpHashParam) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{6}
}

func (x *TcpHashParam) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// TcpGetNonceResponse - response nonce qua TCP (không cần hex parse)
type TcpGetNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpGetNonceResponse) Reset() {
	*x = TcpGetNonceResponse{}
	mi := &file_rpc_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpGetNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpGetNonceResponse) ProtoMessage() {}

func (x *TcpGetNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpGetNonceResponse.ProtoReflect.Descriptor instead.
func (*TcpGetNonceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{7}
}

func (x *TcpGetNonceResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// TcpSubscribeRequest - subscribe events qua TCP
type TcpSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     [][]byte               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"` // contract addresses (mỗi address 20 bytes)
	Topics        [][]byte               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`       // topic hashes (mỗi topic 32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpSubscribeRequest) Reset() {
	*x = TcpSubscribeRequest{}
	mi := &file_rpc_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpSubscribeRequest) ProtoMessage() {}

func (x *TcpSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpSubscribeRequest.ProtoReflect.Descriptor instead.
func (*TcpSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{8}
}

func (x *TcpSubscribeRequest) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *TcpSubscribeRequest) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

// TcpUnsubscribeRequest - unsubscribe qua TCP
type TcpUnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TcpUnsubscribeRequest) Reset() {
	*x = TcpUnsubscribeRequest{}
	mi := &file_rpc_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpUnsubscribeRequest) ProtoMessage() {}

func (x *TcpUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*TcpUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{9}
}

func (x *TcpUnsubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

var File_rpc_request_proto protoreflect.FileDescriptor

const file_rpc_request_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_request.proto\x12\vrpc_request\"f\n" +
	"\n" +
	"RpcRequest\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x03(\fR\x06params\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"|\n" +
	"\vRpcResponse\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.rpc_request.RpcErrorR\x05error\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"L\n" +
	"\bRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\")\n" +
	"\x10TcpSendTxRequest\x12\x15\n" +
	"\x06raw_tx\x18\x01 \x01(\fR\x05rawTx\"7\n" +
	"\x11TcpEthCallRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\fR\x02to\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"+\n" +
	"\x0fTcpAddressParam\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\"\"\n" +
	"\fTcpHashParam\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"+\n" +
	"\x13TcpGetNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"K\n" +
	"\x13TcpSubscribeRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\fR\taddresses\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\fR\x06topics\"@\n" +
	"\x15TcpUnsubscribeRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionIdB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_rpc_request_proto_rawDescOnce sync.Once
	file_rpc_request_proto_rawDescData []byte
)

func file_rpc_request_proto_rawDescGZIP() []byte {
	file_rpc_request_proto_rawDescOnce.Do(func() {
		file_rpc_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_request_proto_rawDesc), len(file_rpc_request_proto_rawDesc)))
	})
	return file_rpc_request_proto_rawDescData
}

var file_rpc_request_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_request_proto_goTypes = []any{
	(*RpcRequest)(nil),            // 0: rpc_request.RpcRequest
	(*RpcResponse)(nil),           // 1: rpc_request.RpcResponse
	(*RpcError)(nil),              // 2: rpc_request.RpcError
	(*TcpSendTxRequest)(nil),      // 3: rpc_request.TcpSendTxRequest
	(*TcpEthCallRequest)(nil),     // 4: rpc_request.TcpEthCallRequest
	(*TcpAddressParam)(nil),       // 5: rpc_request.TcpAddressParam
	(*TcpHashParam)(nil),          // 6: rpc_request.TcpHashParam
	(*TcpGetNonceResponse)(nil),   // 7: rpc_request.TcpGetNonceResponse
	(*TcpSubscribeRequest)(nil),   // 8: rpc_request.TcpSubscribeRequest
	(*TcpUnsubscribeRequest)(nil), // 9: rpc_request.TcpUnsubscribeRequest
}
var file_rpc_request_proto_depIdxs = []int32{
	2, // 0: rpc_request.RpcResponse.error:type_name -> rpc_request.RpcError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_request_proto_init() }
func file_rpc_request_proto_init() {
	if File_rpc_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_request_proto_rawDesc), len(file_rpc_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_request_proto_goTypes,
		DependencyIndexes: file_rpc_request_proto_depIdxs,
		MessageInfos:      file_rpc_request_proto_msgTypes,
	}.Build()
	File_rpc_request_proto = out.File
	file_rpc_request_proto_goTypes = nil
	file_rpc_request_proto_depIdxs = nil
}
