// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: rpc_receipt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcLogEntry - Log entry dùng chung cho cả Event và Receipt
// Tất cả fields dùng string để khớp với chain JSON output (hex format)
type RpcLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address          string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`                   // Contract address
	Topics           []string `protobuf:"bytes,2,rep,name=Topics,proto3" json:"Topics,omitempty"`                     // Topics (event signature + indexed params)
	Data             string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`                         // Non-indexed event data (hex)
	BlockNumber      string   `protobuf:"bytes,4,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`           // Block number (hex)
	TransactionHash  string   `protobuf:"bytes,5,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`   // Transaction hash
	BlockHash        string   `protobuf:"bytes,6,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`               // Block hash
	TransactionIndex string   `protobuf:"bytes,7,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"` // Transaction index (hex)
	LogIndex         string   `protobuf:"bytes,8,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`                 // Log index (hex)
	Removed          bool     `protobuf:"varint,9,opt,name=Removed,proto3" json:"Removed,omitempty"`                  // Removed flag (reorg)
}

func (x *RpcLogEntry) Reset() {
	*x = RpcLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_receipt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcLogEntry) ProtoMessage() {}

func (x *RpcLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcLogEntry.ProtoReflect.Descriptor instead.
func (*RpcLogEntry) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *RpcLogEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RpcLogEntry) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *RpcLogEntry) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RpcLogEntry) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcLogEntry) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcLogEntry) GetLogIndex() string {
	if x != nil {
		return x.LogIndex
	}
	return ""
}

func (x *RpcLogEntry) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// RpcEvent - Subscription event notification = subscription_id + log entry
type RpcEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string       `protobuf:"bytes,1,opt,name=SubscriptionId,proto3" json:"SubscriptionId,omitempty"` // Subscription ID (0xabc...)
	Log            *RpcLogEntry `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`                       // Log entry data
}

func (x *RpcEvent) Reset() {
	*x = RpcEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_receipt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEvent) ProtoMessage() {}

func (x *RpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEvent.ProtoReflect.Descriptor instead.
func (*RpcEvent) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *RpcEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RpcEvent) GetLog() *RpcLogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

// RpcReceipt - Transaction receipt gửi qua TCP (pure protobuf)
type RpcReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionHash   string         `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	From              string         `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                string         `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	ContractAddress   string         `protobuf:"bytes,4,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`            // Nếu deploy contract
	Status            RECEIPT_STATUS `protobuf:"varint,5,opt,name=Status,proto3,enum=receipt.RECEIPT_STATUS" json:"Status,omitempty"` // Dùng enum pb.RECEIPT_STATUS trực tiếp
	GasUsed           string         `protobuf:"bytes,6,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`                            // Hex string
	CumulativeGasUsed string         `protobuf:"bytes,7,opt,name=CumulativeGasUsed,proto3" json:"CumulativeGasUsed,omitempty"`
	EffectiveGasPrice string         `protobuf:"bytes,8,opt,name=EffectiveGasPrice,proto3" json:"EffectiveGasPrice,omitempty"`
	BlockHash         string         `protobuf:"bytes,9,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockNumber       string         `protobuf:"bytes,10,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"` // Hex string
	TransactionIndex  string         `protobuf:"bytes,11,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	Type              string         `protobuf:"bytes,12,opt,name=Type,proto3" json:"Type,omitempty"` // Transaction type
	Logs              []*RpcLogEntry `protobuf:"bytes,13,rep,name=Logs,proto3" json:"Logs,omitempty"` // Dùng chung RpcLogEntry
	LogsBloom         string         `protobuf:"bytes,14,opt,name=LogsBloom,proto3" json:"LogsBloom,omitempty"`
	ReturnData        []byte         `protobuf:"bytes,15,opt,name=ReturnData,proto3" json:"ReturnData,omitempty"` // Return data từ EVM execution
	Exception         string         `protobuf:"bytes,16,opt,name=Exception,proto3" json:"Exception,omitempty"`   // Exception type nếu có lỗi
}

func (x *RpcReceipt) Reset() {
	*x = RpcReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_receipt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReceipt) ProtoMessage() {}

func (x *RpcReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReceipt.ProtoReflect.Descriptor instead.
func (*RpcReceipt) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *RpcReceipt) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcReceipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RpcReceipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RpcReceipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RpcReceipt) GetStatus() RECEIPT_STATUS {
	if x != nil {
		return x.Status
	}
	return RECEIPT_STATUS_RETURNED
}

func (x *RpcReceipt) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *RpcReceipt) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *RpcReceipt) GetEffectiveGasPrice() string {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return ""
}

func (x *RpcReceipt) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcReceipt) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcReceipt) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcReceipt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RpcReceipt) GetLogs() []*RpcLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *RpcReceipt) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

func (x *RpcReceipt) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *RpcReceipt) GetException() string {
	if x != nil {
		return x.Exception
	}
	return ""
}

type GetTransactionReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionHash []byte `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"` // Hash của transaction cần lấy receipt
}

func (x *GetTransactionReceiptRequest) Reset() {
	*x = GetTransactionReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_receipt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptRequest) ProtoMessage() {}

func (x *GetTransactionReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptRequest) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionReceiptRequest) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

// GetTransactionReceiptResponse - Response chứa receipt data
type GetTransactionReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receipt *RpcReceipt `protobuf:"bytes,1,opt,name=Receipt,proto3" json:"Receipt,omitempty"` // RpcReceipt (null nếu không tìm thấy)
	Error   string      `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`     // Error message nếu có lỗi
}

func (x *GetTransactionReceiptResponse) Reset() {
	*x = GetTransactionReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_receipt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptResponse) ProtoMessage() {}

func (x *GetTransactionReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptResponse) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionReceiptResponse) GetReceipt() *RpcReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *GetTransactionReceiptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_rpc_receipt_proto protoreflect.FileDescriptor

var file_rpc_receipt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9f, 0x02, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x2a, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c,
	0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x22, 0x5e, 0x0a, 0x08, 0x52, 0x70, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x4c, 0x6f,
	0x67, 0x22, 0xb5, 0x04, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x28,
	0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x2e, 0x52, 0x45, 0x43, 0x45, 0x49, 0x50, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x61, 0x73,
	0x55, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x61, 0x73, 0x55,
	0x73, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65,
	0x64, 0x12, 0x2c, 0x0a, 0x11, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61,
	0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a,
	0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x70, 0x63, 0x4c,
	0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x45,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x68, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x70, 0x63, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x07,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x5a,
	0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_receipt_proto_rawDescOnce sync.Once
	file_rpc_receipt_proto_rawDescData = file_rpc_receipt_proto_rawDesc
)

func file_rpc_receipt_proto_rawDescGZIP() []byte {
	file_rpc_receipt_proto_rawDescOnce.Do(func() {
		file_rpc_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_receipt_proto_rawDescData)
	})
	return file_rpc_receipt_proto_rawDescData
}

var file_rpc_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_receipt_proto_goTypes = []interface{}{
	(*RpcLogEntry)(nil),                   // 0: rpc_request.RpcLogEntry
	(*RpcEvent)(nil),                      // 1: rpc_request.RpcEvent
	(*RpcReceipt)(nil),                    // 2: rpc_request.RpcReceipt
	(*GetTransactionReceiptRequest)(nil),  // 3: rpc_request.GetTransactionReceiptRequest
	(*GetTransactionReceiptResponse)(nil), // 4: rpc_request.GetTransactionReceiptResponse
	(RECEIPT_STATUS)(0),                   // 5: receipt.RECEIPT_STATUS
}
var file_rpc_receipt_proto_depIdxs = []int32{
	0, // 0: rpc_request.RpcEvent.Log:type_name -> rpc_request.RpcLogEntry
	5, // 1: rpc_request.RpcReceipt.Status:type_name -> receipt.RECEIPT_STATUS
	0, // 2: rpc_request.RpcReceipt.Logs:type_name -> rpc_request.RpcLogEntry
	2, // 3: rpc_request.GetTransactionReceiptResponse.Receipt:type_name -> rpc_request.RpcReceipt
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_receipt_proto_init() }
func file_rpc_receipt_proto_init() {
	if File_rpc_receipt_proto != nil {
		return
	}
	file_receipt_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_receipt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_receipt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_receipt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_receipt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_receipt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_receipt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_receipt_proto_goTypes,
		DependencyIndexes: file_rpc_receipt_proto_depIdxs,
		MessageInfos:      file_rpc_receipt_proto_msgTypes,
	}.Build()
	File_rpc_receipt_proto = out.File
	file_rpc_receipt_proto_rawDesc = nil
	file_rpc_receipt_proto_goTypes = nil
	file_rpc_receipt_proto_depIdxs = nil
}
