// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACTION int32

const (
	ACTION_EMPTY                        ACTION = 0
	ACTION_STAKE                        ACTION = 1
	ACTION_UNSTAKE                      ACTION = 2
	ACTION_DEPLOY_SMART_CONTRACT        ACTION = 3
	ACTION_CALL_SMART_CONTRACT          ACTION = 4
	ACTION_REWARD                       ACTION = 5
	ACTION_PUNISH                       ACTION = 6
	ACTION_MINE                         ACTION = 7
	ACTION_OPEN_CHANNEL                 ACTION = 8
	ACTION_JOIN_CHANNEL                 ACTION = 9
	ACTION_COMMIT_ACCOUNT_STATE_CHANNEL ACTION = 10
	ACTION_COMMIT_CHANNEL               ACTION = 11
	ACTION_UPDATE_STORAGE_HOST          ACTION = 12
)

// Enum value maps for ACTION.
var (
	ACTION_name = map[int32]string{
		0:  "EMPTY",
		1:  "STAKE",
		2:  "UNSTAKE",
		3:  "DEPLOY_SMART_CONTRACT",
		4:  "CALL_SMART_CONTRACT",
		5:  "REWARD",
		6:  "PUNISH",
		7:  "MINE",
		8:  "OPEN_CHANNEL",
		9:  "JOIN_CHANNEL",
		10: "COMMIT_ACCOUNT_STATE_CHANNEL",
		11: "COMMIT_CHANNEL",
		12: "UPDATE_STORAGE_HOST",
	}
	ACTION_value = map[string]int32{
		"EMPTY":                        0,
		"STAKE":                        1,
		"UNSTAKE":                      2,
		"DEPLOY_SMART_CONTRACT":        3,
		"CALL_SMART_CONTRACT":          4,
		"REWARD":                       5,
		"PUNISH":                       6,
		"MINE":                         7,
		"OPEN_CHANNEL":                 8,
		"JOIN_CHANNEL":                 9,
		"COMMIT_ACCOUNT_STATE_CHANNEL": 10,
		"COMMIT_CHANNEL":               11,
		"UPDATE_STORAGE_HOST":          12,
	}
)

func (x ACTION) Enum() *ACTION {
	p := new(ACTION)
	*p = x
	return p
}

func (x ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (ACTION) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACTION.Descriptor instead.
func (ACTION) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

type FEE_TYPE int32

const (
	FEE_TYPE_USER_CHARGE_FEE           FEE_TYPE = 0
	FEE_TYPE_SMART_CONTRACT_CHARGE_FEE FEE_TYPE = 1
)

// Enum value maps for FEE_TYPE.
var (
	FEE_TYPE_name = map[int32]string{
		0: "USER_CHARGE_FEE",
		1: "SMART_CONTRACT_CHARGE_FEE",
	}
	FEE_TYPE_value = map[string]int32{
		"USER_CHARGE_FEE":           0,
		"SMART_CONTRACT_CHARGE_FEE": 1,
	}
)

func (x FEE_TYPE) Enum() *FEE_TYPE {
	p := new(FEE_TYPE)
	*p = x
	return p
}

func (x FEE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FEE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[1].Descriptor()
}

func (FEE_TYPE) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[1]
}

func (x FEE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FEE_TYPE.Descriptor instead.
func (FEE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

type Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ToAddress        []byte                 `protobuf:"bytes,1,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Amount           []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	MaxGas           uint64                 `protobuf:"varint,4,opt,name=MaxGas,proto3" json:"MaxGas,omitempty"`
	MaxGasPrice      uint64                 `protobuf:"varint,5,opt,name=MaxGasPrice,proto3" json:"MaxGasPrice,omitempty"`
	MaxTimeUse       uint64                 `protobuf:"varint,6,opt,name=MaxTimeUse,proto3" json:"MaxTimeUse,omitempty"`
	Data             []byte                 `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	RelatedAddresses [][]byte               `protobuf:"bytes,8,rep,name=RelatedAddresses,proto3" json:"RelatedAddresses,omitempty"`
	LastDeviceKey    []byte                 `protobuf:"bytes,9,opt,name=LastDeviceKey,proto3" json:"LastDeviceKey,omitempty"`
	NewDeviceKey     []byte                 `protobuf:"bytes,10,opt,name=NewDeviceKey,proto3" json:"NewDeviceKey,omitempty"`
	Sign             []byte                 `protobuf:"bytes,11,opt,name=Sign,proto3" json:"Sign,omitempty"`
	Nonce            []byte                 `protobuf:"bytes,12,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	FromAddress      []byte                 `protobuf:"bytes,13,opt,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,14,opt,name=ReadOnly,proto3" json:"ReadOnly,omitempty"`
	// Bổ sung cho giao dịch eth
	ChainID uint64 `protobuf:"varint,15,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	Type    uint64 `protobuf:"varint,16,opt,name=Type,proto3" json:"Type,omitempty"`
	R       []byte `protobuf:"bytes,17,opt,name=R,proto3" json:"R,omitempty"`
	S       []byte `protobuf:"bytes,18,opt,name=S,proto3" json:"S,omitempty"`
	V       []byte `protobuf:"bytes,19,opt,name=V,proto3" json:"V,omitempty"`
	// Thêm cho EIP-1559/EIP-2930
	GasTipCap     []byte         `protobuf:"bytes,20,opt,name=GasTipCap,proto3" json:"GasTipCap,omitempty"`
	GasFeeCap     []byte         `protobuf:"bytes,21,opt,name=GasFeeCap,proto3" json:"GasFeeCap,omitempty"`
	AccessList    []*AccessTuple `protobuf:"bytes,22,rep,name=AccessList,proto3" json:"AccessList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *Transaction) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *Transaction) GetMaxGasPrice() uint64 {
	if x != nil {
		return x.MaxGasPrice
	}
	return 0
}

func (x *Transaction) GetMaxTimeUse() uint64 {
	if x != nil {
		return x.MaxTimeUse
	}
	return 0
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetRelatedAddresses() [][]byte {
	if x != nil {
		return x.RelatedAddresses
	}
	return nil
}

func (x *Transaction) GetLastDeviceKey() []byte {
	if x != nil {
		return x.LastDeviceKey
	}
	return nil
}

func (x *Transaction) GetNewDeviceKey() []byte {
	if x != nil {
		return x.NewDeviceKey
	}
	return nil
}

func (x *Transaction) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *Transaction) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Transaction) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *Transaction) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Transaction) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *Transaction) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Transaction) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Transaction) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Transaction) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Transaction) GetGasTipCap() []byte {
	if x != nil {
		return x.GasTipCap
	}
	return nil
}

func (x *Transaction) GetGasFeeCap() []byte {
	if x != nil {
		return x.GasFeeCap
	}
	return nil
}

func (x *Transaction) GetAccessList() []*AccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

type AccessTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=StorageKeys,proto3" json:"StorageKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTuple) Reset() {
	*x = AccessTuple{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTuple) ProtoMessage() {}

func (x *AccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTuple.ProtoReflect.Descriptor instead.
func (*AccessTuple) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTuple) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccessTuple) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

type TransactionHashData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Amount        []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	MaxGas        uint64                 `protobuf:"varint,4,opt,name=MaxGas,proto3" json:"MaxGas,omitempty"`
	MaxGasPrice   uint64                 `protobuf:"varint,5,opt,name=MaxGasPrice,proto3" json:"MaxGasPrice,omitempty"`
	MaxTimeUse    uint64                 `protobuf:"varint,6,opt,name=MaxTimeUse,proto3" json:"MaxTimeUse,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	Type          uint64                 `protobuf:"varint,8,opt,name=Type,proto3" json:"Type,omitempty"`
	LastDeviceKey []byte                 `protobuf:"bytes,9,opt,name=LastDeviceKey,proto3" json:"LastDeviceKey,omitempty"`
	NewDeviceKey  []byte                 `protobuf:"bytes,10,opt,name=NewDeviceKey,proto3" json:"NewDeviceKey,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,11,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	ChainID       uint64                 `protobuf:"varint,12,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	R             []byte                 `protobuf:"bytes,13,opt,name=R,proto3" json:"R,omitempty"`
	S             []byte                 `protobuf:"bytes,14,opt,name=S,proto3" json:"S,omitempty"`
	V             []byte                 `protobuf:"bytes,15,opt,name=V,proto3" json:"V,omitempty"`
	GasTipCap     []byte                 `protobuf:"bytes,16,opt,name=GasTipCap,proto3" json:"GasTipCap,omitempty"`
	GasFeeCap     []byte                 `protobuf:"bytes,17,opt,name=GasFeeCap,proto3" json:"GasFeeCap,omitempty"`
	AccessList    []*AccessTuple         `protobuf:"bytes,18,rep,name=AccessList,proto3" json:"AccessList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHashData) Reset() {
	*x = TransactionHashData{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHashData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHashData) ProtoMessage() {}

func (x *TransactionHashData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHashData.ProtoReflect.Descriptor instead.
func (*TransactionHashData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionHashData) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *TransactionHashData) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *TransactionHashData) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransactionHashData) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *TransactionHashData) GetMaxGasPrice() uint64 {
	if x != nil {
		return x.MaxGasPrice
	}
	return 0
}

func (x *TransactionHashData) GetMaxTimeUse() uint64 {
	if x != nil {
		return x.MaxTimeUse
	}
	return 0
}

func (x *TransactionHashData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransactionHashData) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TransactionHashData) GetLastDeviceKey() []byte {
	if x != nil {
		return x.LastDeviceKey
	}
	return nil
}

func (x *TransactionHashData) GetNewDeviceKey() []byte {
	if x != nil {
		return x.NewDeviceKey
	}
	return nil
}

func (x *TransactionHashData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TransactionHashData) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *TransactionHashData) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *TransactionHashData) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *TransactionHashData) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *TransactionHashData) GetGasTipCap() []byte {
	if x != nil {
		return x.GasTipCap
	}
	return nil
}

func (x *TransactionHashData) GetGasFeeCap() []byte {
	if x != nil {
		return x.GasFeeCap
	}
	return nil
}

func (x *TransactionHashData) GetAccessList() []*AccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

type DeployData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  []byte                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// string StorageHost = 2; // DEPRECATED
	StorageAddress []byte `protobuf:"bytes,3,opt,name=StorageAddress,proto3" json:"StorageAddress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployData) Reset() {
	*x = DeployData{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployData) ProtoMessage() {}

func (x *DeployData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployData.ProtoReflect.Descriptor instead.
func (*DeployData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *DeployData) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *DeployData) GetStorageAddress() []byte {
	if x != nil {
		return x.StorageAddress
	}
	return nil
}

type CallData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         []byte                 `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallData) Reset() {
	*x = CallData{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallData) ProtoMessage() {}

func (x *CallData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallData.ProtoReflect.Descriptor instead.
func (*CallData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *CallData) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type OpenStateChannelData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddresses [][]byte               `protobuf:"bytes,1,rep,name=ValidatorAddresses,proto3" json:"ValidatorAddresses,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OpenStateChannelData) Reset() {
	*x = OpenStateChannelData{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStateChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStateChannelData) ProtoMessage() {}

func (x *OpenStateChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStateChannelData.ProtoReflect.Descriptor instead.
func (*OpenStateChannelData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *OpenStateChannelData) GetValidatorAddresses() [][]byte {
	if x != nil {
		return x.ValidatorAddresses
	}
	return nil
}

type UpdateStorageHostData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageHost    string                 `protobuf:"bytes,1,opt,name=StorageHost,proto3" json:"StorageHost,omitempty"`
	StorageAddress []byte                 `protobuf:"bytes,2,opt,name=StorageAddress,proto3" json:"StorageAddress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStorageHostData) Reset() {
	*x = UpdateStorageHostData{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageHostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageHostData) ProtoMessage() {}

func (x *UpdateStorageHostData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageHostData.ProtoReflect.Descriptor instead.
func (*UpdateStorageHostData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStorageHostData) GetStorageHost() string {
	if x != nil {
		return x.StorageHost
	}
	return ""
}

func (x *UpdateStorageHostData) GetStorageAddress() []byte {
	if x != nil {
		return x.StorageAddress
	}
	return nil
}

type MassTransferData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MapAddressAmount map[string][]byte      `protobuf:"bytes,1,rep,name=MapAddressAmount,proto3" json:"MapAddressAmount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MassTransferData) Reset() {
	*x = MassTransferData{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassTransferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassTransferData) ProtoMessage() {}

func (x *MassTransferData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassTransferData.ProtoReflect.Descriptor instead.
func (*MassTransferData) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *MassTransferData) GetMapAddressAmount() map[string][]byte {
	if x != nil {
		return x.MapAddressAmount
	}
	return nil
}

type Transactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactions) Reset() {
	*x = Transactions{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactions) ProtoMessage() {}

func (x *Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactions.ProtoReflect.Descriptor instead.
func (*Transactions) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *Transactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type VerifyTransactionSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Sign          []byte                 `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTransactionSignRequest) Reset() {
	*x = VerifyTransactionSignRequest{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTransactionSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTransactionSignRequest) ProtoMessage() {}

func (x *VerifyTransactionSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTransactionSignRequest.ProtoReflect.Descriptor instead.
func (*VerifyTransactionSignRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyTransactionSignRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *VerifyTransactionSignRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *VerifyTransactionSignRequest) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type VerifyTransactionSignResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=Valid,proto3" json:"Valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTransactionSignResult) Reset() {
	*x = VerifyTransactionSignResult{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTransactionSignResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTransactionSignResult) ProtoMessage() {}

func (x *VerifyTransactionSignResult) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTransactionSignResult.ProtoReflect.Descriptor instead.
func (*VerifyTransactionSignResult) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyTransactionSignResult) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *VerifyTransactionSignResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type TransactionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionError) Reset() {
	*x = TransactionError{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionError) ProtoMessage() {}

func (x *TransactionError) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionError.ProtoReflect.Descriptor instead.
func (*TransactionError) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransactionError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransactionHashWithErrorCode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash []byte                 `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Code            int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionHashWithErrorCode) Reset() {
	*x = TransactionHashWithErrorCode{}
	mi := &file_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHashWithErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHashWithErrorCode) ProtoMessage() {}

func (x *TransactionHashWithErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHashWithErrorCode.ProtoReflect.Descriptor instead.
func (*TransactionHashWithErrorCode) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionHashWithErrorCode) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *TransactionHashWithErrorCode) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TransactionWithDeviceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	DeviceKey     []byte                 `protobuf:"bytes,2,opt,name=DeviceKey,proto3" json:"DeviceKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionWithDeviceKey) Reset() {
	*x = TransactionWithDeviceKey{}
	mi := &file_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionWithDeviceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionWithDeviceKey) ProtoMessage() {}

func (x *TransactionWithDeviceKey) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionWithDeviceKey.ProtoReflect.Descriptor instead.
func (*TransactionWithDeviceKey) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionWithDeviceKey) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionWithDeviceKey) GetDeviceKey() []byte {
	if x != nil {
		return x.DeviceKey
	}
	return nil
}

type TransactionsWithBlockNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsWithBlockNumber) Reset() {
	*x = TransactionsWithBlockNumber{}
	mi := &file_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsWithBlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsWithBlockNumber) ProtoMessage() {}

func (x *TransactionsWithBlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsWithBlockNumber.ProtoReflect.Descriptor instead.
func (*TransactionsWithBlockNumber) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionsWithBlockNumber) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionsWithBlockNumber) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type ExecuteSCTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSCTransactions) Reset() {
	*x = ExecuteSCTransactions{}
	mi := &file_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSCTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSCTransactions) ProtoMessage() {}

func (x *ExecuteSCTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSCTransactions.ProtoReflect.Descriptor instead.
func (*ExecuteSCTransactions) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteSCTransactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecuteSCTransactions) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ExecuteSCTransactions) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type FromNodeTransactionsResult struct {
	state                  protoimpl.MessageState          `protogen:"open.v1"`
	ValidTransactionHashes [][]byte                        `protobuf:"bytes,1,rep,name=ValidTransactionHashes,proto3" json:"ValidTransactionHashes,omitempty"`
	TransactionErrors      []*TransactionHashWithErrorCode `protobuf:"bytes,2,rep,name=TransactionErrors,proto3" json:"TransactionErrors,omitempty"`
	BlockNumber            uint64                          `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FromNodeTransactionsResult) Reset() {
	*x = FromNodeTransactionsResult{}
	mi := &file_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromNodeTransactionsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromNodeTransactionsResult) ProtoMessage() {}

func (x *FromNodeTransactionsResult) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromNodeTransactionsResult.ProtoReflect.Descriptor instead.
func (*FromNodeTransactionsResult) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *FromNodeTransactionsResult) GetValidTransactionHashes() [][]byte {
	if x != nil {
		return x.ValidTransactionHashes
	}
	return nil
}

func (x *FromNodeTransactionsResult) GetTransactionErrors() []*TransactionHashWithErrorCode {
	if x != nil {
		return x.TransactionErrors
	}
	return nil
}

func (x *FromNodeTransactionsResult) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type ToNodeTransactionsResult struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ValidTransactionHashes [][]byte               `protobuf:"bytes,1,rep,name=ValidTransactionHashes,proto3" json:"ValidTransactionHashes,omitempty"`
	BlockNumber            uint64                 `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToNodeTransactionsResult) Reset() {
	*x = ToNodeTransactionsResult{}
	mi := &file_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToNodeTransactionsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToNodeTransactionsResult) ProtoMessage() {}

func (x *ToNodeTransactionsResult) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToNodeTransactionsResult.ProtoReflect.Descriptor instead.
func (*ToNodeTransactionsResult) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *ToNodeTransactionsResult) GetValidTransactionHashes() [][]byte {
	if x != nil {
		return x.ValidTransactionHashes
	}
	return nil
}

func (x *ToNodeTransactionsResult) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type TransactionsFromLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	AggSign       []byte                 `protobuf:"bytes,2,opt,name=AggSign,proto3" json:"AggSign,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	TimeStamp     uint64                 `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsFromLeader) Reset() {
	*x = TransactionsFromLeader{}
	mi := &file_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsFromLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsFromLeader) ProtoMessage() {}

func (x *TransactionsFromLeader) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsFromLeader.ProtoReflect.Descriptor instead.
func (*TransactionsFromLeader) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{18}
}

func (x *TransactionsFromLeader) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionsFromLeader) GetAggSign() []byte {
	if x != nil {
		return x.AggSign
	}
	return nil
}

func (x *TransactionsFromLeader) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransactionsFromLeader) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type TransactionHashWithError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`               // Hash của giao dịch gây lỗi
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`              // Mã lỗi
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"` // Mô tả lỗi
	Output        []byte                 `protobuf:"bytes,4,opt,name=Output,proto3" json:"Output,omitempty"`           // chuỗi byte do evm return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHashWithError) Reset() {
	*x = TransactionHashWithError{}
	mi := &file_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHashWithError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHashWithError) ProtoMessage() {}

func (x *TransactionHashWithError) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHashWithError.ProtoReflect.Descriptor instead.
func (*TransactionHashWithError) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *TransactionHashWithError) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TransactionHashWithError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransactionHashWithError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionHashWithError) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\"\xdd\x04\n" +
	"\vTransaction\x12\x1c\n" +
	"\tToAddress\x18\x01 \x01(\fR\tToAddress\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\fR\x06Amount\x12\x16\n" +
	"\x06MaxGas\x18\x04 \x01(\x04R\x06MaxGas\x12 \n" +
	"\vMaxGasPrice\x18\x05 \x01(\x04R\vMaxGasPrice\x12\x1e\n" +
	"\n" +
	"MaxTimeUse\x18\x06 \x01(\x04R\n" +
	"MaxTimeUse\x12\x12\n" +
	"\x04Data\x18\a \x01(\fR\x04Data\x12*\n" +
	"\x10RelatedAddresses\x18\b \x03(\fR\x10RelatedAddresses\x12$\n" +
	"\rLastDeviceKey\x18\t \x01(\fR\rLastDeviceKey\x12\"\n" +
	"\fNewDeviceKey\x18\n" +
	" \x01(\fR\fNewDeviceKey\x12\x12\n" +
	"\x04Sign\x18\v \x01(\fR\x04Sign\x12\x14\n" +
	"\x05Nonce\x18\f \x01(\fR\x05Nonce\x12 \n" +
	"\vFromAddress\x18\r \x01(\fR\vFromAddress\x12\x1a\n" +
	"\bReadOnly\x18\x0e \x01(\bR\bReadOnly\x12\x18\n" +
	"\aChainID\x18\x0f \x01(\x04R\aChainID\x12\x12\n" +
	"\x04Type\x18\x10 \x01(\x04R\x04Type\x12\f\n" +
	"\x01R\x18\x11 \x01(\fR\x01R\x12\f\n" +
	"\x01S\x18\x12 \x01(\fR\x01S\x12\f\n" +
	"\x01V\x18\x13 \x01(\fR\x01V\x12\x1c\n" +
	"\tGasTipCap\x18\x14 \x01(\fR\tGasTipCap\x12\x1c\n" +
	"\tGasFeeCap\x18\x15 \x01(\fR\tGasFeeCap\x128\n" +
	"\n" +
	"AccessList\x18\x16 \x03(\v2\x18.transaction.AccessTupleR\n" +
	"AccessList\"I\n" +
	"\vAccessTuple\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12 \n" +
	"\vStorageKeys\x18\x02 \x03(\fR\vStorageKeys\"\x89\x04\n" +
	"\x13TransactionHashData\x12 \n" +
	"\vFromAddress\x18\x01 \x01(\fR\vFromAddress\x12\x1c\n" +
	"\tToAddress\x18\x02 \x01(\fR\tToAddress\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\fR\x06Amount\x12\x16\n" +
	"\x06MaxGas\x18\x04 \x01(\x04R\x06MaxGas\x12 \n" +
	"\vMaxGasPrice\x18\x05 \x01(\x04R\vMaxGasPrice\x12\x1e\n" +
	"\n" +
	"MaxTimeUse\x18\x06 \x01(\x04R\n" +
	"MaxTimeUse\x12\x12\n" +
	"\x04Data\x18\a \x01(\fR\x04Data\x12\x12\n" +
	"\x04Type\x18\b \x01(\x04R\x04Type\x12$\n" +
	"\rLastDeviceKey\x18\t \x01(\fR\rLastDeviceKey\x12\"\n" +
	"\fNewDeviceKey\x18\n" +
	" \x01(\fR\fNewDeviceKey\x12\x14\n" +
	"\x05Nonce\x18\v \x01(\fR\x05Nonce\x12\x18\n" +
	"\aChainID\x18\f \x01(\x04R\aChainID\x12\f\n" +
	"\x01R\x18\r \x01(\fR\x01R\x12\f\n" +
	"\x01S\x18\x0e \x01(\fR\x01S\x12\f\n" +
	"\x01V\x18\x0f \x01(\fR\x01V\x12\x1c\n" +
	"\tGasTipCap\x18\x10 \x01(\fR\tGasTipCap\x12\x1c\n" +
	"\tGasFeeCap\x18\x11 \x01(\fR\tGasFeeCap\x128\n" +
	"\n" +
	"AccessList\x18\x12 \x03(\v2\x18.transaction.AccessTupleR\n" +
	"AccessList\"H\n" +
	"\n" +
	"DeployData\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\fR\x04Code\x12&\n" +
	"\x0eStorageAddress\x18\x03 \x01(\fR\x0eStorageAddress\" \n" +
	"\bCallData\x12\x14\n" +
	"\x05Input\x18\x01 \x01(\fR\x05Input\"F\n" +
	"\x14OpenStateChannelData\x12.\n" +
	"\x12ValidatorAddresses\x18\x01 \x03(\fR\x12ValidatorAddresses\"a\n" +
	"\x15UpdateStorageHostData\x12 \n" +
	"\vStorageHost\x18\x01 \x01(\tR\vStorageHost\x12&\n" +
	"\x0eStorageAddress\x18\x02 \x01(\fR\x0eStorageAddress\"\xb8\x01\n" +
	"\x10MassTransferData\x12_\n" +
	"\x10MapAddressAmount\x18\x01 \x03(\v23.transaction.MassTransferData.MapAddressAmountEntryR\x10MapAddressAmount\x1aC\n" +
	"\x15MapAddressAmountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"L\n" +
	"\fTransactions\x12<\n" +
	"\fTransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\fTransactions\"^\n" +
	"\x1cVerifyTransactionSignRequest\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\x12\x16\n" +
	"\x06Pubkey\x18\x02 \x01(\fR\x06Pubkey\x12\x12\n" +
	"\x04Sign\x18\x03 \x01(\fR\x04Sign\"G\n" +
	"\x1bVerifyTransactionSignResult\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\x12\x14\n" +
	"\x05Valid\x18\x02 \x01(\bR\x05Valid\"H\n" +
	"\x10TransactionError\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"\\\n" +
	"\x1cTransactionHashWithErrorCode\x12(\n" +
	"\x0fTransactionHash\x18\x01 \x01(\fR\x0fTransactionHash\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"t\n" +
	"\x18TransactionWithDeviceKey\x12:\n" +
	"\vTransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vTransaction\x12\x1c\n" +
	"\tDeviceKey\x18\x02 \x01(\fR\tDeviceKey\"}\n" +
	"\x1bTransactionsWithBlockNumber\x12<\n" +
	"\fTransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\fTransactions\x12 \n" +
	"\vBlockNumber\x18\x02 \x01(\x04R\vBlockNumber\"\x91\x01\n" +
	"\x15ExecuteSCTransactions\x12<\n" +
	"\fTransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\fTransactions\x12\x18\n" +
	"\aGroupId\x18\x02 \x01(\x04R\aGroupId\x12 \n" +
	"\vBlockNumber\x18\x03 \x01(\x04R\vBlockNumber\"\xcf\x01\n" +
	"\x1aFromNodeTransactionsResult\x126\n" +
	"\x16ValidTransactionHashes\x18\x01 \x03(\fR\x16ValidTransactionHashes\x12W\n" +
	"\x11TransactionErrors\x18\x02 \x03(\v2).transaction.TransactionHashWithErrorCodeR\x11TransactionErrors\x12 \n" +
	"\vBlockNumber\x18\x03 \x01(\x04R\vBlockNumber\"t\n" +
	"\x18ToNodeTransactionsResult\x126\n" +
	"\x16ValidTransactionHashes\x18\x01 \x03(\fR\x16ValidTransactionHashes\x12 \n" +
	"\vBlockNumber\x18\x03 \x01(\x04R\vBlockNumber\"\xb0\x01\n" +
	"\x16TransactionsFromLeader\x12<\n" +
	"\fTransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\fTransactions\x12\x18\n" +
	"\aAggSign\x18\x02 \x01(\fR\aAggSign\x12 \n" +
	"\vBlockNumber\x18\x03 \x01(\x04R\vBlockNumber\x12\x1c\n" +
	"\tTimeStamp\x18\x04 \x01(\x04R\tTimeStamp\"|\n" +
	"\x18TransactionHashWithError\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x16\n" +
	"\x06Output\x18\x04 \x01(\fR\x06Output*\xf4\x01\n" +
	"\x06ACTION\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\t\n" +
	"\x05STAKE\x10\x01\x12\v\n" +
	"\aUNSTAKE\x10\x02\x12\x19\n" +
	"\x15DEPLOY_SMART_CONTRACT\x10\x03\x12\x17\n" +
	"\x13CALL_SMART_CONTRACT\x10\x04\x12\n" +
	"\n" +
	"\x06REWARD\x10\x05\x12\n" +
	"\n" +
	"\x06PUNISH\x10\x06\x12\b\n" +
	"\x04MINE\x10\a\x12\x10\n" +
	"\fOPEN_CHANNEL\x10\b\x12\x10\n" +
	"\fJOIN_CHANNEL\x10\t\x12 \n" +
	"\x1cCOMMIT_ACCOUNT_STATE_CHANNEL\x10\n" +
	"\x12\x12\n" +
	"\x0eCOMMIT_CHANNEL\x10\v\x12\x17\n" +
	"\x13UPDATE_STORAGE_HOST\x10\f*>\n" +
	"\bFEE_TYPE\x12\x13\n" +
	"\x0fUSER_CHARGE_FEE\x10\x00\x12\x1d\n" +
	"\x19SMART_CONTRACT_CHARGE_FEE\x10\x01B3\n" +
	")com.meta_node.protos.compiled.transactionZ\x06/protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_transaction_proto_goTypes = []any{
	(ACTION)(0),                          // 0: transaction.ACTION
	(FEE_TYPE)(0),                        // 1: transaction.FEE_TYPE
	(*Transaction)(nil),                  // 2: transaction.Transaction
	(*AccessTuple)(nil),                  // 3: transaction.AccessTuple
	(*TransactionHashData)(nil),          // 4: transaction.TransactionHashData
	(*DeployData)(nil),                   // 5: transaction.DeployData
	(*CallData)(nil),                     // 6: transaction.CallData
	(*OpenStateChannelData)(nil),         // 7: transaction.OpenStateChannelData
	(*UpdateStorageHostData)(nil),        // 8: transaction.UpdateStorageHostData
	(*MassTransferData)(nil),             // 9: transaction.MassTransferData
	(*Transactions)(nil),                 // 10: transaction.Transactions
	(*VerifyTransactionSignRequest)(nil), // 11: transaction.VerifyTransactionSignRequest
	(*VerifyTransactionSignResult)(nil),  // 12: transaction.VerifyTransactionSignResult
	(*TransactionError)(nil),             // 13: transaction.TransactionError
	(*TransactionHashWithErrorCode)(nil), // 14: transaction.TransactionHashWithErrorCode
	(*TransactionWithDeviceKey)(nil),     // 15: transaction.TransactionWithDeviceKey
	(*TransactionsWithBlockNumber)(nil),  // 16: transaction.TransactionsWithBlockNumber
	(*ExecuteSCTransactions)(nil),        // 17: transaction.ExecuteSCTransactions
	(*FromNodeTransactionsResult)(nil),   // 18: transaction.FromNodeTransactionsResult
	(*ToNodeTransactionsResult)(nil),     // 19: transaction.ToNodeTransactionsResult
	(*TransactionsFromLeader)(nil),       // 20: transaction.TransactionsFromLeader
	(*TransactionHashWithError)(nil),     // 21: transaction.TransactionHashWithError
	nil,                                  // 22: transaction.MassTransferData.MapAddressAmountEntry
}
var file_transaction_proto_depIdxs = []int32{
	3,  // 0: transaction.Transaction.AccessList:type_name -> transaction.AccessTuple
	3,  // 1: transaction.TransactionHashData.AccessList:type_name -> transaction.AccessTuple
	22, // 2: transaction.MassTransferData.MapAddressAmount:type_name -> transaction.MassTransferData.MapAddressAmountEntry
	2,  // 3: transaction.Transactions.Transactions:type_name -> transaction.Transaction
	2,  // 4: transaction.TransactionWithDeviceKey.Transaction:type_name -> transaction.Transaction
	2,  // 5: transaction.TransactionsWithBlockNumber.Transactions:type_name -> transaction.Transaction
	2,  // 6: transaction.ExecuteSCTransactions.Transactions:type_name -> transaction.Transaction
	14, // 7: transaction.FromNodeTransactionsResult.TransactionErrors:type_name -> transaction.TransactionHashWithErrorCode
	2,  // 8: transaction.TransactionsFromLeader.Transactions:type_name -> transaction.Transaction
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
