// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: validator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// StringStringPair định nghĩa một cặp key-value dạng chuỗi để thay thế cho map,
// nhằm đảm bảo việc tuần tự hóa tất định (canonical encoding).
type StringStringPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStringPair) Reset() {
	*x = StringStringPair{}
	mi := &file_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStringPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringPair) ProtoMessage() {}

func (x *StringStringPair) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringPair.ProtoReflect.Descriptor instead.
func (*StringStringPair) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{1}
}

func (x *StringStringPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StringStringPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ValidatorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*Validator           `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorList) Reset() {
	*x = ValidatorList{}
	mi := &file_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorList) ProtoMessage() {}

func (x *ValidatorList) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorList.ProtoReflect.Descriptor instead.
func (*ValidatorList) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorList) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

// Validator định nghĩa cấu trúc dữ liệu on-chain cho một validator.
type Validator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Địa chỉ Ethereum của validator.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Tên hiển thị của validator.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Mô tả chi tiết về validator.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Trang web của validator.
	Website string `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	// Trạng thái bị "jail" (tạm khóa).
	IsJailed bool `protobuf:"varint,5,opt,name=is_jailed,json=isJailed,proto3" json:"is_jailed,omitempty"`
	// Thời điểm hết hạn "jail".
	JailedUntil *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=jailed_until,json=jailedUntil,proto3" json:"jailed_until,omitempty"`
	// Bộ đếm các khối đã bỏ lỡ liên tiếp.
	MissedBlocksCounter int64 `protobuf:"varint,7,opt,name=missed_blocks_counter,json=missedBlocksCounter,proto3" json:"missed_blocks_counter,omitempty"`
	// Tỷ lệ hoa hồng (ví dụ: 1000 tương đương 10%). Tối đa 10000.
	CommissionRate uint64 `protobuf:"varint,8,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	// Lượng stake tối thiểu validator phải tự ủy quyền (dưới dạng chuỗi).
	MinSelfDelegation string `protobuf:"bytes,9,opt,name=min_self_delegation,json=minSelfDelegation,proto3" json:"min_self_delegation,omitempty"`
	// Danh sách chứa các delegator và lượng stake của họ.
	// Được sắp xếp theo key (địa chỉ delegator) trước khi marshal để đảm bảo tính tất định.
	Delegators []*StringStringPair `protobuf:"bytes,10,rep,name=delegators,proto3" json:"delegators,omitempty"`
	// Tổng phần thưởng tích lũy trên mỗi đơn vị stake (nhân với 10^18).
	AccumulatedRewardsPerShare string `protobuf:"bytes,11,opt,name=accumulated_rewards_per_share,json=accumulatedRewardsPerShare,proto3" json:"accumulated_rewards_per_share,omitempty"`
	// Chỉ số phần thưởng của từng delegator tại lần cuối họ tương tác.
	// Được sắp xếp theo key (địa chỉ delegator) trước khi marshal để đảm bảo tính tất định.
	DelegatorRewardIndexes []*StringStringPair `protobuf:"bytes,12,rep,name=delegator_reward_indexes,json=delegatorRewardIndexes,proto3" json:"delegator_reward_indexes,omitempty"`
	// URL tới ảnh đại diện của validator.
	Image             string `protobuf:"bytes,13,opt,name=image,proto3" json:"image,omitempty"`
	PrimaryAddress    string `protobuf:"bytes,14,opt,name=primary_address,json=primaryAddress,proto3" json:"primary_address,omitempty"`
	TotalStakedAmount string `protobuf:"bytes,15,opt,name=total_staked_amount,json=totalStakedAmount,proto3" json:"total_staked_amount,omitempty"`
	WorkerAddress     string `protobuf:"bytes,16,opt,name=worker_address,json=workerAddress,proto3" json:"worker_address,omitempty"`
	P2PAddress        string `protobuf:"bytes,17,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	PubkeyBls         string `protobuf:"bytes,18,opt,name=pubkey_bls,json=pubkeyBls,proto3" json:"pubkey_bls,omitempty"`
	PubkeySecp        string `protobuf:"bytes,19,opt,name=pubkey_secp,json=pubkeySecp,proto3" json:"pubkey_secp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{3}
}

func (x *Validator) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Validator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Validator) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Validator) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Validator) GetIsJailed() bool {
	if x != nil {
		return x.IsJailed
	}
	return false
}

func (x *Validator) GetJailedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.JailedUntil
	}
	return nil
}

func (x *Validator) GetMissedBlocksCounter() int64 {
	if x != nil {
		return x.MissedBlocksCounter
	}
	return 0
}

func (x *Validator) GetCommissionRate() uint64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

func (x *Validator) GetMinSelfDelegation() string {
	if x != nil {
		return x.MinSelfDelegation
	}
	return ""
}

func (x *Validator) GetDelegators() []*StringStringPair {
	if x != nil {
		return x.Delegators
	}
	return nil
}

func (x *Validator) GetAccumulatedRewardsPerShare() string {
	if x != nil {
		return x.AccumulatedRewardsPerShare
	}
	return ""
}

func (x *Validator) GetDelegatorRewardIndexes() []*StringStringPair {
	if x != nil {
		return x.DelegatorRewardIndexes
	}
	return nil
}

func (x *Validator) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Validator) GetPrimaryAddress() string {
	if x != nil {
		return x.PrimaryAddress
	}
	return ""
}

func (x *Validator) GetTotalStakedAmount() string {
	if x != nil {
		return x.TotalStakedAmount
	}
	return ""
}

func (x *Validator) GetWorkerAddress() string {
	if x != nil {
		return x.WorkerAddress
	}
	return ""
}

func (x *Validator) GetP2PAddress() string {
	if x != nil {
		return x.P2PAddress
	}
	return ""
}

func (x *Validator) GetPubkeyBls() string {
	if x != nil {
		return x.PubkeyBls
	}
	return ""
}

func (x *Validator) GetPubkeySecp() string {
	if x != nil {
		return x.PubkeySecp
	}
	return ""
}

// Thêm một loại request/response mới để làm ví dụ
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_validator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{4}
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_validator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStatus) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ServerStatus) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof đảm bảo chỉ một trong các trường sau có thể được set tại một thời điểm
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_BlockRequest
	//	*Request_StatusRequest
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_validator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetBlockRequest() *BlockRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_BlockRequest); ok {
			return x.BlockRequest
		}
	}
	return nil
}

func (x *Request) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_BlockRequest struct {
	BlockRequest *BlockRequest `protobuf:"bytes,1,opt,name=block_request,json=blockRequest,proto3,oneof"`
}

type Request_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,2,opt,name=status_request,json=statusRequest,proto3,oneof"` // Thêm các loại request khác ở đây trong tương lai
}

func (*Request_BlockRequest) isRequest_Payload() {}

func (*Request_StatusRequest) isRequest_Payload() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_ValidatorList
	//	*Response_ServerStatus
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_validator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetValidatorList() *ValidatorList {
	if x != nil {
		if x, ok := x.Payload.(*Response_ValidatorList); ok {
			return x.ValidatorList
		}
	}
	return nil
}

func (x *Response) GetServerStatus() *ServerStatus {
	if x != nil {
		if x, ok := x.Payload.(*Response_ServerStatus); ok {
			return x.ServerStatus
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_ValidatorList struct {
	ValidatorList *ValidatorList `protobuf:"bytes,1,opt,name=validator_list,json=validatorList,proto3,oneof"`
}

type Response_ServerStatus struct {
	ServerStatus *ServerStatus `protobuf:"bytes,2,opt,name=server_status,json=serverStatus,proto3,oneof"` // Thêm các loại response khác ở đây
}

func (*Response_ValidatorList) isResponse_Payload() {}

func (*Response_ServerStatus) isResponse_Payload() {}

var File_validator_proto protoreflect.FileDescriptor

const file_validator_proto_rawDesc = "" +
	"\n" +
	"\x0fvalidator.proto\x12\x05state\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\fBlockRequest\x12 \n" +
	"\vblockNumber\x18\x01 \x01(\x04R\vblockNumber\":\n" +
	"\x10StringStringPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\rValidatorList\x120\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x10.state.ValidatorR\n" +
	"validators\"\xa4\x06\n" +
	"\tValidator\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x1b\n" +
	"\tis_jailed\x18\x05 \x01(\bR\bisJailed\x12=\n" +
	"\fjailed_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vjailedUntil\x122\n" +
	"\x15missed_blocks_counter\x18\a \x01(\x03R\x13missedBlocksCounter\x12'\n" +
	"\x0fcommission_rate\x18\b \x01(\x04R\x0ecommissionRate\x12.\n" +
	"\x13min_self_delegation\x18\t \x01(\tR\x11minSelfDelegation\x127\n" +
	"\n" +
	"delegators\x18\n" +
	" \x03(\v2\x17.state.StringStringPairR\n" +
	"delegators\x12A\n" +
	"\x1daccumulated_rewards_per_share\x18\v \x01(\tR\x1aaccumulatedRewardsPerShare\x12Q\n" +
	"\x18delegator_reward_indexes\x18\f \x03(\v2\x17.state.StringStringPairR\x16delegatorRewardIndexes\x12\x14\n" +
	"\x05image\x18\r \x01(\tR\x05image\x12'\n" +
	"\x0fprimary_address\x18\x0e \x01(\tR\x0eprimaryAddress\x12.\n" +
	"\x13total_staked_amount\x18\x0f \x01(\tR\x11totalStakedAmount\x12%\n" +
	"\x0eworker_address\x18\x10 \x01(\tR\rworkerAddress\x12\x1f\n" +
	"\vp2p_address\x18\x11 \x01(\tR\n" +
	"p2pAddress\x12\x1d\n" +
	"\n" +
	"pubkey_bls\x18\x12 \x01(\tR\tpubkeyBls\x12\x1f\n" +
	"\vpubkey_secp\x18\x13 \x01(\tR\n" +
	"pubkeySecp\"\x0f\n" +
	"\rStatusRequest\"\\\n" +
	"\fServerStatus\x12%\n" +
	"\x0estatus_message\x18\x01 \x01(\tR\rstatusMessage\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x04R\ruptimeSeconds\"\x8f\x01\n" +
	"\aRequest\x12:\n" +
	"\rblock_request\x18\x01 \x01(\v2\x13.state.BlockRequestH\x00R\fblockRequest\x12=\n" +
	"\x0estatus_request\x18\x02 \x01(\v2\x14.state.StatusRequestH\x00R\rstatusRequestB\t\n" +
	"\apayload\"\x90\x01\n" +
	"\bResponse\x12=\n" +
	"\x0evalidator_list\x18\x01 \x01(\v2\x14.state.ValidatorListH\x00R\rvalidatorList\x12:\n" +
	"\rserver_status\x18\x02 \x01(\v2\x13.state.ServerStatusH\x00R\fserverStatusB\t\n" +
	"\apayloadB\bZ\x06/protob\x06proto3"

var (
	file_validator_proto_rawDescOnce sync.Once
	file_validator_proto_rawDescData []byte
)

func file_validator_proto_rawDescGZIP() []byte {
	file_validator_proto_rawDescOnce.Do(func() {
		file_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)))
	})
	return file_validator_proto_rawDescData
}

var file_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_validator_proto_goTypes = []any{
	(*BlockRequest)(nil),          // 0: state.BlockRequest
	(*StringStringPair)(nil),      // 1: state.StringStringPair
	(*ValidatorList)(nil),         // 2: state.ValidatorList
	(*Validator)(nil),             // 3: state.Validator
	(*StatusRequest)(nil),         // 4: state.StatusRequest
	(*ServerStatus)(nil),          // 5: state.ServerStatus
	(*Request)(nil),               // 6: state.Request
	(*Response)(nil),              // 7: state.Response
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_validator_proto_depIdxs = []int32{
	3, // 0: state.ValidatorList.validators:type_name -> state.Validator
	8, // 1: state.Validator.jailed_until:type_name -> google.protobuf.Timestamp
	1, // 2: state.Validator.delegators:type_name -> state.StringStringPair
	1, // 3: state.Validator.delegator_reward_indexes:type_name -> state.StringStringPair
	0, // 4: state.Request.block_request:type_name -> state.BlockRequest
	4, // 5: state.Request.status_request:type_name -> state.StatusRequest
	2, // 6: state.Response.validator_list:type_name -> state.ValidatorList
	5, // 7: state.Response.server_status:type_name -> state.ServerStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_validator_proto_init() }
func file_validator_proto_init() {
	if File_validator_proto != nil {
		return
	}
	file_validator_proto_msgTypes[6].OneofWrappers = []any{
		(*Request_BlockRequest)(nil),
		(*Request_StatusRequest)(nil),
	}
	file_validator_proto_msgTypes[7].OneofWrappers = []any{
		(*Response_ValidatorList)(nil),
		(*Response_ServerStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validator_proto_goTypes,
		DependencyIndexes: file_validator_proto_depIdxs,
		MessageInfos:      file_validator_proto_msgTypes,
	}.Build()
	File_validator_proto = out.File
	file_validator_proto_goTypes = nil
	file_validator_proto_depIdxs = nil
}
